- src/backend/config/tools.py
**Description:** rename tools - remove source
> Config: rename tools

- CONTRIBUTING.md
**Description:** update how to contribute - point to forks instead of branches
> Docs: update how to contribute

- src/backend/chat/custom/model_deployments/deployment.py
**Description:** instead of using Cohere Platform, defaults the deployment to the first available in the list
> Deployment: default to first available deployment

- .github/workflows/python-lint.yml
- cli/main.py
**Description:** 
- improve tool prompt by adding a generic function
- add isort version to github action so it matches `make lint`
> CLI: improve tool prompt

- README.md
- docs/deployment_guides/single_container.md
> chore:update readme to fix single container run command

- README.md
- docs/deployment_guides/single_container.md
- Fixing the README link for Azure one-click deployment
> Azure one-click deployment - link fix

- src/backend/chat/custom/model_deployments/azure.py
- src/backend/tests/conftest.py
- src/backend/tests/model_deployments/conftest.py
- src/backend/tests/model_deployments/mock_deployments/__init__.py
- src/backend/tests/model_deployments/mock_deployments/mock_azure.py
- src/backend/tests/model_deployments/test_azure.py
- src/backend/tests/model_deployments/test_cohere_platform.py
- src/backend/tests/model_deployments/test_sagemaker.py
- src/backend/tests/routers/test_deployment.py
Testing: Azure
Backend: AzureDeployment logic
> Add Mock Azure testing, testing improvements

- src/interfaces/coral_web/src/hooks/os.ts
> coral-web: fix typo in os.ts

- README.md
Description: document change only
> docs: change the deployment instructions 

- docker_scripts/env-defaults
- docker_scripts/functions
- docs/deployment_guides/single_container.md
- standalone.Dockerfile
- Standalone Docker improvements
- Pass ENV variables in .env file during runtime.
> Standalone Docker improvements

- README.md
- docs/deployment_guides/aws_ecs_single_container.md
- docs/deployment_guides/aws_ecs_single_container_ec2.md
- AWS ECS EC2 deployment instructions
> AWS ECS EC2 deployment

- README.md
> docs: duplicate deploy button

- src/interfaces/coral_web/src/hooks/streamChat.ts
> coral-web: fix experimental features hook import

- src/community/model_deployments/hugging_face.py
**Description:** Fix hugging face return types
> Deployment: fix hugging face deployment

- README.md
- docker_scripts/env-defaults
- docs/deployment_guides/single_container.md
- standalone.Dockerfile
- Azure one click deployment description
- Single docker improvements
> readme: add Azure deployment description + single Docker improvements and fixes

- README.md
Updating README links that still point to outdated `cohere-ai/toolkit` repository.
- **Description:** Updating README links that still point to outdated `cohere-ai/toolkit` repository.
- **Issue:** No issues associated.
- **Dependencies:** No changes required.
> docs: Update README.md links

- README.md
> docs: clarify setup env for development.

- README.md
Add Windows and MacOS e2e setup instructions
> Docs: add env setup instructions

- README.md
- docs/command_model_providers.md
- docs/how_to_guides.md
- docs/service_deployments.md
- docs/setup.md
- docs/troubleshooting.md
Cleans up and updates the documentation
> Update documentation 

- Makefile
- docs/setup.md
**Description**: There is a wrong path on makefile setup as well as  the windows setup instructions, this just fixes that
> docs: Update setup.md and makefile instruction to point to the right path

- src/backend/cli/main.py
- src/community/config/tools.py
> CLI: fix default values

- src/backend/cli/main.py
- Couple small updates to the CLI
> backend: Update CLI

- README.md
Add generated image of contributors to README.md
> Readme: add contributors

- src/backend/cli/main.py
Multiple people said it's confusing once they arrive at the variable review section of the CLI.
> chore: enter to continue on env var review

- docs/deployment_guides/gcp_deployment.md
> Small updates to GCP deploy guide

- README.md
- docs/auth_guide.md
> Docs: Add documentation for setting up Authentication

- docs/deployment_guides/gcp_deployment.md
> Clarify GCP docs

- .github/pull_request_template.md
This PR updates the pull request template for the Cohere Toolkit repository.
- Adds a new section, "AI Description," to the template, which will be automatically maintained by command-r-plus.
- This section will be overwritten by the command as the PR is updated and can be opted out by deleting the section.
> Add pr-pal to template

- README.md
one-liner change
This pull request updates the `README.md` file with additional instructions for cloning and running the repository locally. 
- Added a `cd cohere-toolkit` command to the existing `git clone` command in the example code for cloning and running the repository locally.
> documentation: make it a bit smoother

- docs/setup.md
- Setup documentation improvements 
The pull request makes changes to the setup instructions for Windows systems.
The PR updates the setup steps for Windows, focusing on streamlining the process and ensuring compatibility. It replaces `pipx` with `miniconda` for improved package management and removes the separate installation of `pipx`, `poetry`, and `miniconda`, opting for a consolidated approach. It also standardizes the installation of `poetry` and its version across steps.
- Replaces steps 4 and 5 with a consolidated installation of `miniconda` using `scoop`.
- Removes the separate installation of `pipx`.
- Standardizes the installation command for `poetry` to use `pip install` instead of `pipx install`.
- Removes the redundant installation of `miniconda` in step …
> Improvements to Windows setup documentation

- docs/custom_tool_guides/tool_guide.md
This pull request updates a link in the documentation for implementing a custom tool.
- Updates the link for adding tool implementations in the "Step 3: Implement the Tool" section.
> Fixed link in tool_guide.md

- docs/postman/Toolkit.postman_collection.json
Postman collection did not reflect changes made to the enpoints, such as adding `v1` to the route
This PR updates the `docs/postman/Toolkit.postman_collection.json` file.
The changes in this PR update the Postman Collection file (`Toolkit.postman_collection.json`) to use a different schema version and modify the URLs for some of the API requests.
- Updates the `_postman_id` and `schema` fields in the `info` object.
- Modifies the `url` field for several API requests, including changes to the path and removal of the `protocol`, `host`, and `port` fields.
- Removes the `header` field for one of the API requests.
- Adds a `url` field for an API request that previously did not have one.
> Docs: fix postman collection

- src/interfaces/coral_web/src/cohere-client/client.ts
- src/interfaces/coral_web/src/components/Agents/AgentCard.tsx
- src/interfaces/coral_web/src/components/Conversation/Header.tsx
- src/interfaces/coral_web/src/components/Conversation/index.tsx
- src/interfaces/coral_web/src/components/ConversationList/ConversationCard.tsx
- src/interfaces/coral_web/src/components/ConversationList/ConversationListHeader.tsx
- src/interfaces/coral_web/src/components/ConversationList/ConversationListPanel.tsx
- src/interfaces/coral_web/src/hooks/chat.ts
- src/interfaces/coral_web/src/hooks/route.ts
- src/interfaces/coral_web/src/hooks/streamChat.ts
- src/interfaces/coral_web/src/pages/agents/[agentId]/c/[conversationId]/index.tsx
- src/interfaces/coral_web/src/pages/agents/[agentId]/index.tsx
- src/interfaces/coral_web/src/pages/agents/c/[conversationId]/index.tsx
- src/interfaces/coral_web/src/pages/agents/index.tsx
- src/interfaces/coral_web/src/pages/c/[id]/index.tsx
https://github.com/cohere-ai/cohere-toolkit/assets/10562610/12f38f2c-ea91-428e-9c51-85a386bb76e9
> frontend: allow to switch and load agent conversations

- helper_scripts/metrics_helper.py
- src/backend/routers/user.py
- src/backend/services/metrics.py
This pull request updates the `get_success()` function in the `metrics.py` and `metrics_helper.py` files.
The `get_success()` function now returns `True` for status codes in the range of `[200, 300)` instead of `[200, 400)`. This change aligns the function with the standard convention that status codes in the 200 range indicate a successful response.
- …
> Metrics: fix success code

- src/backend/routers/conversation.py
- src/backend/tests/routers/test_conversation.py
The `upload_file` function in `conversation.py` has been modified to include error handling and file deletion after uploading. 
- The code now uses a `try-except` block to handle potential exceptions during file uploading. If an exception occurs, an `HTTPException` is raised with a status code of 500 and a detailed error message.
- After successfully …
> File: remove local file after upload

- src/backend/config/tools.py
The PR makes changes to the `src/backend/config/tools.py` file, specifically to the `ToolName` class.
The changes in this PR involve renaming and reordering some of the tools within the `ToolName` class. The tool previously named "Calculator" has been renamed to "Py Expression Eval," and the tool order has been rearranged, moving "Tavily Internet …
> Tools: rename and sort

- src/backend/services/chat.py
The `get_or_create_conversation` function in `chat.py` has been updated to include a new parameter, `user_message`, and to set the `title` attribute of the `Conversation` object based on the first five words of the `user_message`.
- The `get_or_create_conversation` function now includes a new parameter, `user_message`, which is used to set the `title` …
> Chat: update conversation title

- src/backend/chat/custom/custom.py
Remove the file tools when no files are attached to avoid hallucination
The PR makes changes to the `call_chat` and `get_managed_tools` functions in `custom.py`.
The changes ensure that files are added to the chat history only if the tool requires it and files are provided. If no files are provided, the Read_File and Search_File tools are removed as a temporary workaround.
- In the `call_chat` function:
- Added a check for `chat_request.file_ids` before adding files to the chat history.
- Introduced a temporary workaround to remove the Read_File and Search_File tools if no files are provided.
- In the `get_managed_tools` function:
- Removed the `get_tool_calls` function, which previously added files to the chat history if the Read_File or Search_File tools were present.
> Chat: fix infinite loop

- .github/workflows/docker_push_backend.yml
- .github/workflows/docker_push_frontend.yml
- src/backend/Dockerfile
- src/interfaces/coral_web/Dockerfile
Adding build targets for frontend & backend.
> Add build targets for backend / frontend

- src/backend/services/chat.py
- src/backend/tests/crud/test_agent_tool_metadata.py
- src/interfaces/coral_web/Dockerfile
- src/interfaces/coral_web/package.json
- src/interfaces/coral_web/src/components/Conversation/Composer/WebSearchConfigurationModal.tsx
+ fix test_agent_tool_metadata
+ catching error in Agent validation for now
+ started work for prod target build, however next.js doesn't finish "starting" with `start` command instead of `dev` (missing workflow change once ready)
> Some fixes for agents + tools

- src/backend/database_models/conversation.py
The `messages` property in the `Conversation` class now sorts messages based on their `created_at` timestamp instead of their `position`.
- `src/backend/database_models/conversation.py`
> Conversation: sort messages

- src/interfaces/coral_web/src/cohere-client/client.ts
- src/interfaces/coral_web/src/cohere-client/constants.ts
- src/interfaces/coral_web/src/cohere-client/utils.ts
- src/interfaces/coral_web/src/components/Agents/AgentForm.tsx
- src/interfaces/coral_web/src/components/Agents/AgentsSidePanel.tsx
- src/interfaces/coral_web/src/components/Agents/Layout.tsx
- src/interfaces/coral_web/src/components/Agents/MobileHeader.tsx
- src/interfaces/coral_web/src/components/Agents/UpdateAgentPanel.tsx
- src/interfaces/coral_web/src/components/Conversation/MessagingContainer.tsx
- src/interfaces/coral_web/src/components/Conversation/index.tsx
- src/interfaces/coral_web/src/components/ConversationList/ConversationCard.tsx
- src/interfaces/coral_web/src/components/ConversationList/ConversationListPanel.tsx
- src/interfaces/coral_web/src/components/ConversationList/ConversationListPanelGroup.tsx
- src/interfaces/coral_web/src/hooks/chat.ts
- src/interfaces/coral_web/src/hooks/conversation.tsx
- src/interfaces/coral_web/src/hooks/streamChat.ts
- src/interfaces/coral_web/tailwind.config.js
**Description:** 
This PR tackles some UI bugs:
- show latest message as description
- update description whenever sending messages
- ~sort messages by when they were sent -> messages from BE are returned out of order~
- return finish reason error properly
- fix edit agent panel animation
- [mobile] edit agent panel large padding
- [mobile] add hamburger button for opening agents list panel
- [mobile] agents list panel positioning
**Before**
https://github.com/cohere-ai/cohere-toolkit/assets/5898755/5e42f8cc-9b1c-4436-86d6-9047e2db72b1
**After**
https://github.com/cohere-ai/cohere-toolkit/assets/5898755/7601e337-71c9-41c6-9679-8dcea67c18dd
https://github.com/cohere-ai/cohere-toolkit/assets/5898755/06a3073c-0289-4844-9cb9-c13c499ac050
This PR makes changes to the …
> coral-web: fix various UI bugs

- src/backend/routers/agent.py
This pull request introduces a new function, `create_agent`, within the `src/backend/routers/agent.py` module. 
The `create_agent` function enables the creation of a new agent by accepting specific arguments and returning the created agent. It is designed to interact with the database and handle agent-related operations. 
- Added the `create_agent` …
> docs: add back docstring

- .env-template
- .github/scripts/run_docker_migration.sh
- .github/scripts/run_src_migration.sh
- .github/workflows/run_alembic_migrations.yml
- README.md
- docs/github_migrations_action.md
- src/backend/config/auth.py
- src/backend/main.py
- Github workflow to automate alembic migrations.
This PR introduces automated database migrations using GitHub Actions. It sets up the necessary scripts and configuration files to enable migrations through different methods, such as SSH access to a remote server, connection strings, and Cohere Toolkit's API migrations endpoint.
- Adds a new section in the `.env-template` file to include the `MIGRATE_TOKEN` used for authenticating requests to the migrate endpoint.
- Creates two new shell scripts, `run_docker_migration.sh` and `run_src_migration.sh`, in the `.github/scripts` directory to handle migrations using Docker and source code, respectively.
- Introduces a new GitHub Actions workflow file, `run_alembic_migrations.yml`, which defines the steps for running Alembic …
> Automated migrations workflow(optionally SSH, Database URL or API call)

- src/interfaces/coral_web/Dockerfile
- src/interfaces/coral_web/src/components/MessageContent.tsx
- src/interfaces/coral_web/src/components/Shared/Markdown/Markdown.tsx
This pull request makes changes to the `src/interfaces/coral_web` directory, specifically to the `Dockerfile`, `MessageContent.tsx`, and `Markdown.tsx` files.
- In the `Dockerfile`, the `FROM base AS prod` and `CMD npm run start` lines are now commented out.
- In `MessageContent.tsx`, the `Markdown` component now includes an additional prop, `renderRawHtml`, which is set to `false`.
- `Markdown.tsx` has been updated to include a new prop, `renderRawHtml`, in the `MarkdownTextProps` type and the `getActiveMarkdownPlugins` function. The function now accepts an object with `renderRawHtml` and `renderLaTex` properties. Depending on the value of `renderRawHtml`, the `getActiveMarkdownPlugins` function adds or removes specific plugins from the `rehypePlugins` array.
> fix(tookit): tags in chat history are getting removed after submitting

- src/interfaces/coral_web/src/components/Shared/CodeSnippet/CodeSnippet.tsx
- src/interfaces/coral_web/src/components/Shared/Markdown/tags/Iframe.tsx
- src/interfaces/coral_web/src/utils/preview.ts
https://github.com/cohere-ai/cohere-toolkit/assets/19353218/dd1f1d9f-3f2d-4ab4-808d-204de3ab05ad
This pull request updates the ``CodeSnippet` component to support HTML syntax highlighting and makes changes to the ``Iframe` component to use the ``TabGroup` and ``TabPanel` from `@headlessui/react`.
- Added ``import xml from 'react-syntax-highlighter/dist/cjs/languages/hljs/xml';` to support HTML syntax highlighting in the `CodeSnippet` component.
- Updated the ``lang` prop type in `CodeSnippet` to include 'html'.
- Registered the 'html' language with the `SyntaxHighlighter` by adding ``SyntaxHighlighter.registerLanguage('html', xml);`.
- Modified the ``mapLangToSyntaxHighlighterLang` function to include a case for 'html'.
- Updated the `Iframe` component to use the …
> feat(toolkit): Improve artifacts UI

- src/backend/chat/custom/custom.py
- src/backend/services/logger.py
The PR introduces changes to the logging mechanism in the backend of a chat application. 
**Files Affected:**
- `src/backend/chat/custom/custom.py`
- `src/backend/services/logger.py`
**Changes:**
- The `send_log_message` function is imported and utilized in `custom.py` to standardize log messages.
- Log messages now include additional details such as …
> Logs: add more logs to chat

- src/backend/services/metrics.py
The pull request makes changes to the `metrics.py` file in the backend services of a project. Specifically, it modifies several functions responsible for collecting metrics and performance data.
The PR updates the code to use `asyncio.run()` instead of `await` when calling the `run_loop()` function. This change allows the asynchronous `run_loop()` …
> Metrics: return sync generator

- src/backend/routers/snapshot.py
- src/backend/schemas/snapshot.py
- src/backend/services/snapshot.py
- src/backend/tests/routers/test_snapshot.py
This pull request introduces changes to the snapshot creation process, adding the `SnapshotAgent` and `SnapshotData` models and updating the `create_snapshot` function to use these models.
- The `SnapshotAgent` and `SnapshotData` classes are added to the `src/backend/schemas/snapshot.py` module, defining the structure of snapshot agents and data …
> Snapshot: improve types

- src/backend/routers/snapshot.py
- src/backend/schemas/conversation.py
- src/backend/schemas/snapshot.py
- src/backend/schemas/tool.py
- src/backend/services/snapshot.py
- src/backend/tests/routers/test_snapshot.py
This pull request makes changes to three Python files: `conversation.py`, `tool.py`, and `snapshot.py`. 
- The `messages` and `files` fields in the `Conversation` class are now optional and can be of type `List[Message]` or `Optional[List[Message]]`.
- The `Conversation` class now includes a new field called `text_messages`, which is also optional and …
> Snapshot: fix conversations with tools

- src/interfaces/coral_web/src/cohere-client/client.ts
- src/interfaces/coral_web/src/components/ToolEvents.tsx
- src/interfaces/coral_web/src/hooks/streamChat.ts
- src/interfaces/coral_web/src/pages/_app.tsx
- src/interfaces/coral_web/src/pages/login.tsx
- Redirect the user to log in when facing 401.
- Catch errors send from chat-request and forward them to the chat history
- Fix layout on event message found urls
Closes OS-2232
> fix(frontend): redirect on 401

- src/backend/chat/collate.py
- src/backend/chat/custom/custom.py
- src/backend/model_deployments/azure.py
- src/backend/model_deployments/base.py
- src/backend/model_deployments/bedrock.py
- src/backend/model_deployments/cohere_platform.py
- src/backend/model_deployments/sagemaker.py
- src/backend/model_deployments/single_container.py
- src/backend/routers/conversation.py
- src/backend/services/chat.py
- src/backend/services/metrics.py
- src/backend/tests/tools/test_collate.py
- src/community/model_deployments/hugging_face.py
- src/community/model_deployments/local_model.py
This PR introduces changes to the backend and community model deployment modules. The changes include:
- **Asyncio**: The code has been updated to use `async` and `await` for asynchronous operations, improving concurrency and potentially enhancing performance.
- **Typing**: The `typing` module has been updated to use `AsyncGenerator` instead of …
> Metrics: make everything async

- src/backend/config/routers.py
This PR updates the `poetry.lock` file and makes changes to the `src/backend/config/routers.py` file. 
The `poetry.lock` file has been updated to the latest version of Poetry (1.8.3). This file is automatically generated and should not be changed manually. The update includes:
- An upgrade of the `certifi` package from version `2024.6.2` to `2024.7.4`. …
> backend(chore): add session dependency on tools router

- src/backend/tools/python_interpreter.py
The `call` method in the `PythonInterpreter` class now includes the `async` keyword, indicating that it is an asynchronous function. This change suggests that the function may involve some form of waiting or I/O operation, such as making a network request or reading/writing to a file. 
- `src/backend/tools/python_interpreter.py`: Modified the …
> Python interpreter: make call async

- src/backend/chat/custom/custom.py
- src/backend/config/routers.py
- src/backend/config/tools.py
- src/backend/model_deployments/azure.py
- src/backend/model_deployments/bedrock.py
- src/backend/model_deployments/cohere_platform.py
- src/backend/model_deployments/sagemaker.py
- src/backend/model_deployments/single_container.py
- src/backend/services/metrics.py
- src/backend/tools/__init__.py
- src/backend/tools/tavily.py
- src/backend/tools/web_scrape.py
- Adding scraping to web search
- Adding web scrape tool
- Fix kwargs passing that has been causing chat and rerank calls to fail
This PR makes changes to the following:
- Environment variables
- Docker configuration
- Pre-commit hooks
- Makefile commands
- Dependency versions
- Function signatures
- Function implementations
- Model deployments
- Tool definitions
- Database queries
The following environment variables have been added:
- COHERE_COMPASS_USERNAME
- COHERE_COMPASS_PASSWORD
- COHERE_COMPASS_API_URL
- <co: 0>COHERE_COMPASS_PARSER_URL
> backend: web scraping in tools + fix metrics data use in tools

- src/backend/main.py
- src/backend/model_deployments/cohere_platform.py
> Metrics: test deployment without metrics

- src/backend/chat/collate.py
- src/backend/chat/custom/custom.py
- src/backend/main.py
- src/backend/model_deployments/cohere_platform.py
- src/backend/services/chat.py
- src/backend/tools/python_interpreter.py
- src/backend/tools/tavily.py
This PR removes the `async` keyword from several functions and methods, effectively converting them to synchronous functions. Additionally, it includes some commented-out middleware lines in `src/backend/main.py`.
- `rerank_and_chunk` in `src/backend/chat/collate.py`
- `chat`, `call_chat`, `call_tools`, and `handle_tool_calls_stream` in …
> Test sync code

- src/interfaces/coral_web/src/hooks/tools.ts
Validate that the files/folders selected follow the limitations of the tool.
- Do not allow mix of files and folders
- When user upload files, allow max 5
- When user select folders, allow unlimited folders
- When user select folders, allow unlimited folders
> fix(toolkit): Limit GDrive file/folders upload

- src/interfaces/coral_web/src/cohere-client/client.ts
- src/interfaces/coral_web/src/cohere-client/generated/schemas.gen.ts
- src/interfaces/coral_web/src/cohere-client/generated/services.gen.ts
- src/interfaces/coral_web/src/cohere-client/generated/types.gen.ts
- src/interfaces/coral_web/src/components/Citations/Citation.tsx
- src/interfaces/coral_web/src/components/Conversation/Header.tsx
- src/interfaces/coral_web/src/components/MessageRow.tsx
- src/interfaces/coral_web/src/components/ReadOnlyConversation.tsx
- src/interfaces/coral_web/src/components/ShareModal.tsx
- src/interfaces/coral_web/src/constants.ts
- src/interfaces/coral_web/src/hooks/snapshots.ts
- src/interfaces/coral_web/src/pages/share/[id]/index.tsx
- src/interfaces/coral_web/src/utils/conversation.ts
- src/interfaces/coral_web/src/utils/error.ts
- src/interfaces/coral_web/tailwind.config.js
Porting share links from Coral with addition of tool events + citations
https://github.com/cohere-ai/cohere-toolkit/assets/140425731/af8a9380-62c2-4322-a04b-3121854c4a02
https://github.com/cohere-ai/cohere-toolkit/assets/140425731/b1df033a-0e0e-4185-969f-c1ac9fd4f2a8
This PR introduces a new feature that allows users to create, view, and share snapshots of conversations. It also adds a "Share" option to the conversation header menu, enabling users to generate and share links to their conversations.
- `src/interfaces/coral_web/src/cohere-client/client.ts`: Adds snapshot-related methods to the `CohereClient` class.
- `src/interfaces/coral_web/src/cohere-client/generated/schemas.gen.ts`: Updates the `$Snapshot` type and adds new types for snapshot-related data structures. …
> coral-web: share conversations

- src/backend/chat/collate.py
- src/backend/chat/custom/custom.py
- src/backend/main.py
- src/backend/model_deployments/cohere_platform.py
- src/backend/routers/chat.py
- src/backend/services/chat.py
- src/backend/tests/routers/test_conversation.py
- src/backend/tools/python_interpreter.py
- src/backend/tools/tavily.py
The PR introduces changes to multiple Python files in the `src/backend` directory. The primary modification involves converting several functions to `async def` and updating their return types to `AsyncGenerator`. This change is made to accommodate asynchronous operations and improve the handling of streams and generators.
- …
> Make everything async again

- src/backend/config/auth.py
- src/backend/config/deployments.py
This pull request makes changes to the backend configuration, specifically related to authentication and deployment strategies.
The PR updates the `ENABLED_AUTH_STRATEGIES` list by removing the `OpenIDConnect` strategy, essentially disabling it. It also includes some code reorganization for the `ModelDeploymentName` class in the `deployments.py` file, …
> Update config 

- src/backend/crud/agent.py
- src/backend/crud/agent_tool_metadata.py
- src/backend/routers/agent.py
- src/backend/routers/utils.py
- src/backend/schemas/agent.py
- src/backend/services/agent.py
- src/backend/services/transaction.py
- src/backend/tests/crud/test_agent.py
- src/backend/tests/crud/test_agent_tool_metadata.py
- src/backend/tests/routers/test_agent.py
This PR introduces changes to the agent and agent tool metadata management. 
The following modifications are made:
- Added `try-except` blocks to the `create_agent`, `get_agent_by_id`, `get_agent_by_name`, `get_agents`, `update_agent`, and `delete_agent` functions in `src/backend/crud/agent.py. This change ensures that any exceptions that occur during …
> Agents: remove user_id and org_id + refactor

- src/interfaces/coral_web/src/components/ToolEvents.tsx
- src/interfaces/coral_web/src/utils/urls.ts
This pull request updates the `ToolEvents.tsx` and `urls.ts` components to use the new `getValidURL` utility function.
The `ToolEvents` component now uses the `getValidURL` function to retrieve valid URLs from the `stream_search_results`. It also updates the text displayed when referencing artifacts to "Referenced the following resources:" instead of "Found the following resources:".
The `getValidURL` function is added to the `urls.ts` utility module. This function validates a given URL and returns it if it is valid. If the URL is invalid, it returns `undefined`.
- Updates `ToolEvents.tsx` to use the `getValidURL` function.
- Adds the `getValidURL` function to `urls.ts`.
> fix(toolkit): fix broken links to files

- src/interfaces/coral_web/src/app/(main)/(chat)/Chat.tsx
This pull request updates the `Chat.tsx` component in the `coral_web` interface. 
The pull request makes changes to the `Chat` component, which appears to be part of a React application. The `Chat` component utilizes several hooks and context providers from the application's custom hooks and stores. 
- Removes the `useChatRoutes` hook import.
- Updates the dependency array of the `useEffect` hook by adding `conversation?.messages.length` and removing `conversation?.id`.
> fix(toolkit): issue with conversation history not updating

- src/backend/model_deployments/cohere_platform.py
> Cohere Platform: enable rerank

- src/backend/tools/google_drive/auth.py
The `try_refresh_token` function in `auth.py` has been updated to include additional parameters when creating a new `UpdateToolAuth` object.
This change adds the `user_id` and `tool_id` parameters to the `UpdateToolAuth` object, ensuring that the user and tool information is included in the token refresh process.
- The `user_id` …
> GDrive auth fix

- src/interfaces/assistants_web/src/components/Agents/AgentForm.tsx
- src/interfaces/assistants_web/src/components/ConversationList/ConversationListHeader.tsx
- src/interfaces/assistants_web/src/components/Settings/FilesTab.tsx
- src/interfaces/assistants_web/src/components/Shared/Checkbox/Checkbox.tsx
- src/interfaces/assistants_web/src/components/Shared/RadioGroup/RadioGroup.tsx
- src/interfaces/assistants_web/src/components/Shared/RadioGroup/index.ts
- src/interfaces/assistants_web/src/components/Shared/Switch/Switch.tsx
- src/interfaces/assistants_web/src/components/Shared/index.ts
https://github.com/user-attachments/assets/c5ce456f-4f88-427b-b1ac-1b7537b15bb7
https://github.com/user-attachments/assets/f68df521-44c4-4286-8b71-e9a8e0032522
https://github.com/user-attachments/assets/12acb8ed-8716-4bd6-8c03-bdd79e403f56
This pull request updates the Checkbox, Switch, and RadioGroup components in the shared components library and updates the AgentForm, ConversationListHeader, and FilesTab components in the assistants_web interface.
- **Checkbox component updates:**
- The onChange prop now expects a function that takes a checked boolean as an argument instead of a React.ChangeEvent<HTMLInputElement>>.
- The size and theme props have been removed, and the theme prop has been replaced with a new theme prop that accepts different values.
- The dataTestId …
> feat(toolkit): New dark mode components

- src/interfaces/assistants_web/src/components/Conversation/Composer/ComposerToolbar.tsx
- src/interfaces/coral_web/src/components/Conversation/Composer/ComposerToolbar.tsx
- style: update composer files tooltip
Closes TLK-856
> frontend(web): update composer attaching file tooltip

- src/interfaces/assistants_web/src/app/healthz/api/route.tsx
- src/interfaces/assistants_web/src/app/healthz/page.tsx
- src/interfaces/coral_web/src/app/healthz/api/route.tsx
- src/interfaces/coral_web/src/app/healthz/page.tsx
This pull request adds a new health check endpoint to the application. 
**Changes:**
- Introduces a new `GET` function in `route.tsx` that returns a `200 OK` response.
- Adds a new `HealthzPage` component in `page.tsx` that renders an "OK" message.
> feat(toolkit): add health check route

- src/interfaces/assistants_web/package-lock.json
- src/interfaces/assistants_web/package.json
- src/interfaces/assistants_web/src/app/(main)/settings/page.tsx
- src/interfaces/assistants_web/src/components/Agents/DiscoverAgentCard.tsx
- src/interfaces/assistants_web/src/components/Agents/DiscoverAgents.tsx
- src/interfaces/assistants_web/src/components/Agents/Settings.tsx
- src/interfaces/assistants_web/src/components/ConnectDataModal.tsx
- src/interfaces/assistants_web/src/components/DarkMode/index.tsx
- src/interfaces/assistants_web/src/components/DarkMode/style.css
- src/interfaces/assistants_web/src/components/Shared/Switch/Switch.tsx
- src/interfaces/assistants_web/src/components/Shared/Tabs/Tabs.tsx
- feat: settings page
- not done: delete connection (backends need to be done)
- not done: re-sync (backends need to be done)
- feat: dark mode toggle (not persisting)
Closes TLK-872
https://github.com/user-attachments/assets/70990332-819e-4e3c-8bd1-82a9633eefe9
> toolkit(assistants): settings page + dark mode toggle

- src/backend/schemas/context.py
- src/backend/schemas/metrics.py
- src/backend/services/metrics.py
- src/backend/tests/routers/test_chat.py
- src/backend/tests/routers/test_conversation.py
- **Logs: add context**
- **simplify conversation id**
- **simplify agent id**
- **add test coverage for chat and ranking durations**
This PR introduces a `Context class to store request-specific information. It also modifies the existing code to use this class for storing and retrieving context information.
The `Context` class is defined in …
> metrics: test coverage for chat and rerank durations

- src/backend/chat/custom/custom.py
This pull request makes changes to the `call_chat` function in `custom.py`.
The `call_chat` function has been updated to use the `ctx` object to access the conversation ID and user ID when adding files to the chat history. This change ensures that the correct IDs are used when retrieving the necessary information from the context.
- In …
> Context: use conv id correctly

- src/backend/chat/custom/custom.py
The `custom.py` file in the `src/backend/chat/custom/` directory has been updated. 
The `custom.py` file now includes the `to_dict` function from the `backend.chat.collate` module. 
- The `from backend.chat.collate import rerank_and_chunk` line has been modified to include `, to_dict`.
> Logs: fix import

- src/backend/routers/organization.py
- src/backend/services/cache.py
- src/backend/tools/google_drive/auth.py
This pull request updates the `get_logger` import statement in multiple backend Python scripts. 
**Changes:**
- In `src/backend/routers/organization.py`, `src/backend/services/cache.py`, and `src/backend/tools/google_drive/auth.py`, the import statement `from backend.services.logger import get_logger` has been changed to `from …
> backend: fix logger import

- Makefile
- src/backend/services/cache.py
- src/backend/tests/routers/test_user.py
- src/backend/tests/services/test_cache.py
The pull request updates the error logging mechanism in the `get_client` function of the `cache.py` file. 
**Changes:**
- Updates the `logger.error` statement to include the `event` keyword argument, providing more context for the error message.
> Logs: fix cache log

- src/interfaces/assistants_web/src/components/DarkMode/style.css
Updates dark mode animation
https://github.com/user-attachments/assets/0b110035-44f5-4b63-960d-37d624b871fd
> frontend(assistants_web): update dark mode animation

- src/backend/config/configuration.template.yaml
- Configuration template fix 
The pull request makes several updates to the `configuration.template.yaml` file in the backend source code. 
- Adds an `api_key` field under `cohere_platform`.
- Introduces an `api_key` field under the newly added `web_search` section, which replaces the `tavily` section.
- Appends an `app_id` field under the `wolfram_alpha` section.
- Includes a `strategy: structlog` field under the `logger` section.
> Configuration template fix

- src/backend/crud/user.py
This PR makes changes to the database schema and includes some adjustments to Alembic commands. 
- The ``groups` and `user_group` tables are dropped and then recreated with some changes. 
- The `users` table is altered to include a `user_name` and an `active` column. 
- The `files` table is renamed to `message_files` and its schema is modified. 
- A new …
> feat: use user active column

- src/backend/schemas/agent.py
This pull request updates the `AgentPublic` class in the `agent.py` file.
The PR removes the `user_id` field from the `AgentPublic` class, which is a subclass of the `Agent` class.
- Removed the `user_id` field from the `AgentPublic` class.
> Agents: add user id to response

- src/backend/chat/custom/custom.py
The PR makes changes to the `call_chat` async function in `custom.py`. 
The changes relate to how files are handled when adding them to a chat history. Instead of adding files to the chat history unconditionally, the updated code first checks if any files are available. If files are available, they are added to the chat history, and the `Read_File` and …
> Files: remove file tools when no files are provided

- src/interfaces/assistants_web/src/components/Agents/AgentSettings/AgentSettingsForm.tsx
Remove skip from agent update and creation steps.
> fix(toolkit): remove skip

- src/interfaces/assistants_web/src/app/_providers.tsx
- src/interfaces/assistants_web/src/components/Agents/AgentCard.tsx
- src/interfaces/assistants_web/src/components/ConversationList/ConversationCard.tsx
- src/interfaces/assistants_web/src/components/DarkModeToggle/index.tsx
- src/interfaces/assistants_web/src/components/Shared/Markdown/Markdown.tsx
- src/interfaces/assistants_web/src/hooks/chatRoutes.ts
- src/interfaces/assistants_web/tailwind.config.js
- fix: inline code char for dark mode in markdown
- feat: add system appearance option
- fix: only closes left panel when is on mobile
Closes TLK-956 TLK-957 TLK-962
https://github.com/user-attachments/assets/4deed3f5-3c21-4dee-b0a4-35f9ff163698
> frontend(web): bug bash 

- src/backend/tools/tavily.py
The pull request makes a change to the `call` function in the `tavily.py` backend tool. Specifically, it modifies the format of the returned list by:
- Adding a new key-value pair `"title": result ["title"]` to the dictionary in the list.
> Citations: add title to web search

- charts/cohere-toolkit/templates/_helpers.tpl
This pull request makes changes to the `charts/cohere-toolkit/templates/_helpers.tpl` file.
The pull request updates the `printf` function in the `_helpers.tpl` file to adjust the format of the Redis connection string.
- Modified the `printf` function in the `charts/cohere-toolkit/templates/_helpers.tpl` file to rearrange the format of the Redis …
> fix: redis host (for real)

- src/interfaces/assistants_web/Dockerfile
This pull request updates the `Dockerfile` in the `assistants_web` interface to include a new production-specific target.
The `RUN npm run build` command has been added to the `Dockerfile`, allowing for the creation of a production-specific image. This image will be used as a base for running the start command in a production environment.
- Added `RUN …
> fix(toolkit): add build step dockerfile

- src/interfaces/assistants_web/src/env.mjs
The PR updates the `skipValidation` array in the `env.mjs` file to include an additional string value, 'build'. 
- The `skipValidation` array now includes 'build' alongside existing values: 'lint', 'format', 'test', 'test:coverage', and 'test:watch'.
> fix(toolkit): skip checking env vars during build for dockerfile

- src/interfaces/assistants_web/src/app/share/[id]/page.tsx
- src/interfaces/assistants_web/src/cohere-client/generated/schemas.gen.ts
- src/interfaces/assistants_web/src/cohere-client/generated/services.gen.ts
- src/interfaces/assistants_web/src/cohere-client/generated/types.gen.ts
- src/interfaces/assistants_web/src/components/Agents/AgentSettings/AgentSettingsForm.tsx
- src/interfaces/assistants_web/src/components/Agents/AgentSettings/VisibilityStep.tsx
- src/interfaces/assistants_web/src/components/Agents/CreateAgent.tsx
- src/interfaces/assistants_web/src/components/Agents/LeftPanel.tsx
- src/interfaces/assistants_web/src/components/Agents/Settings.tsx
- src/interfaces/assistants_web/src/components/Agents/UpdateAgent.tsx
- src/interfaces/assistants_web/src/components/Conversation/Composer/DataSourceMenu.tsx
- src/interfaces/assistants_web/src/components/Conversation/index.tsx
- src/interfaces/assistants_web/src/components/DarkModeToggle/index.tsx
- src/interfaces/assistants_web/src/components/MessageFile.tsx
- src/interfaces/assistants_web/src/components/ReadOnlyConversation.tsx
- src/interfaces/assistants_web/src/components/Shared/HotKeys/HotKeysDialog.tsx
- src/interfaces/assistants_web/src/components/Shared/RadioGroup/RadioGroup.tsx
- src/interfaces/assistants_web/src/components/Shared/Tabs/Tabs.tsx
- src/interfaces/assistants_web/src/components/WelcomePage.tsx
- Allow to update the visibility of already created agent.
- run format
- generate api schema
- update width of dark mode boxes
Closes TLK-968
> feat(web): allow to update the visibility of already created agent

- src/interfaces/assistants_web/package-lock.json
- src/interfaces/assistants_web/package.json
- src/interfaces/assistants_web/src/env.mjs
- src/interfaces/coral_web/package-lock.json
- src/interfaces/coral_web/package.json
- src/interfaces/coral_web/src/env.mjs
> fix(toolkit): docker env vars

- src/backend/chat/custom/tool_calls.py
- src/backend/tests/chat/test_tool_calls.py
The `_call_tool_async` function in `tool_calls.py` has been modified to improve error handling and provide more detailed information when a tool call fails. 
- The `event` log now includes the name of the tool that failed to call, along with the error message. 
- Instead of raising an `HTTPException`, the function now returns an `outputs` list …
> Pass error back into the model 

- src/interfaces/assistants_web/src/app/(main)/(chat)/Chat.tsx
- src/interfaces/assistants_web/src/app/(main)/(chat)/layout.tsx
- src/interfaces/assistants_web/src/components/Agents/AgentSettings/AgentSettingsForm.tsx
- src/interfaces/assistants_web/src/components/Conversation/index.tsx
- src/interfaces/assistants_web/src/components/Shared/RadioGroup/RadioGroup.tsx
- src/interfaces/assistants_web/src/hooks/files.ts
- src/interfaces/assistants_web/src/hooks/streamChat.ts
- src/interfaces/assistants_web/src/stores/slices/paramsSlice.ts
Closes TLK-988
Couple of bug fixes/improvements:
- Fixes a bug when adding files to a new conversation
- Radio Component now accepts clicking on label
- Reset Files Params no longer reset tools
> fix(toolkit): file upload for new conversations

- src/interfaces/assistants_web/src/components/MarkdownImage.tsx
- src/interfaces/assistants_web/src/components/MessageContent.tsx
- src/interfaces/assistants_web/src/components/MessageRow.tsx
- src/interfaces/assistants_web/src/components/Shared/Text/Text.tsx
- src/interfaces/assistants_web/src/hooks/chat.ts
- src/interfaces/assistants_web/src/hooks/streamChat.ts
- fix: save output files after receiving them on the search results event
- fix: accent color on show steps button
- refactor: early return to improve readability
- feat: increase the accessibility of images
Closes TLK-984
> fix: save output files after receiving them on search results event

- src/interfaces/assistants_web/src/app/share/[id]/page.tsx
- src/interfaces/assistants_web/src/components/Citations/Citation.tsx
- src/interfaces/assistants_web/src/components/ToolEvents.tsx
- src/interfaces/assistants_web/src/hooks/conversation.tsx
- src/interfaces/assistants_web/src/hooks/snapshots.ts
fix: align icon and description
feat: add a link to the title in the citation dialog
feat: show python-generated images in the shared conversation
fix(🤦): filter the actual removed conversation from the list
Closes TLK-992
> feat: show python-generated images into share conversations

- charts/cohere-toolkit/Chart.yaml
- charts/cohere-toolkit/templates/backend.yaml
This pull request updates the `version` in `Chart.yaml` and adds a `BROKER_URL` to the `stringData` block in `backend.yaml`.
Updates the `version` in `Chart.yaml` to `0.2.2` to reflect changes made to the chart and its templates. Additionally, a `BROKER_URL` is added to the `stringData` block in `backend.yaml`, ensuring consistent formatting with other URL entries.
- Increments the `version` in `Chart.yaml` to `0.2.2`.
- Adds a `BROKER_URL` to the `stringData` block in `backend.yaml`.
> infra: Added Broker URL To Backend

- src/backend/crud/agent.py
specfic -> specific
This pull request makes a small correction to the docstring in the `create_agent` function in `src/backend/crud/agent.py`.
A typo in the docstring of the `create_agent` function is fixed by changing "specfic" to "specific".
- `src/backend/crud/agent.py`: Typo fix in the docstring of the `create_agent` function.
> chore: update agent.py

- CODEOWNERS
The PR updates the `CODEOWNERS` file, which specifies the owners of various source code files in the repository.
- Adds `@BeatrixCohere` as a new owner for the `src/interfaces/coral_web` and `src/interfaces/assistants_web` sections.
> Add myself to codeowners 

- docs/auth_guide.md
- docs/how_to_guides.md
- docs/setup.md
Still lots to do but updates docs to reference config settings
> Update docs to reference config file

- src/interfaces/assistants_web/src/cohere-client/client.ts
- src/interfaces/assistants_web/src/cohere-client/generated/schemas.gen.ts
- src/interfaces/assistants_web/src/cohere-client/generated/services.gen.ts
- src/interfaces/assistants_web/src/cohere-client/generated/types.gen.ts
- src/interfaces/assistants_web/src/components/Agents/Settings.tsx
- src/interfaces/assistants_web/src/hooks/chat.ts
- src/interfaces/assistants_web/src/hooks/files.ts
- src/interfaces/assistants_web/src/hooks/tools.ts
- src/interfaces/assistants_web/src/stores/slices/filesSlice.ts
- src/interfaces/assistants_web/src/types/message.ts
- Generate API client
- feat: allow to delete an auth tool.
Closes TLK-1001
> feat: allow to delete an auth tool

- src/backend/tools/files.py
This pull request updates the `FileToolsArtifactTypes` class in the `src/backend/tools/files.py` module. Specifically, it:
- Renames the `local_file` attribute in the `FileToolsArtifactTypes` class to `file'.
> fix agent files chat 

- src/interfaces/assistants_web/src/components/Agents/LeftPanel.tsx
- src/interfaces/assistants_web/src/components/Welcome.tsx
- fix: rename tooltip
- fix: change "Your private assistant" to "Your public assistant"
Closes TLK-1019
> fix: small nits

- src/interfaces/assistants_web/src/components/Agents/LeftPanel.tsx
- src/interfaces/assistants_web/src/components/Citations/Citation.tsx
- src/interfaces/assistants_web/src/components/Citations/CitationTextHighlighter.tsx
- src/interfaces/assistants_web/tailwind.config.js
UI feedback 
- Make LeftPanel size fit perfectly for 5 assistants
- Make citations header use the branded color for the assistant
> fix(toolkit): UI nits feedback

- src/interfaces/assistants_web/src/components/Shared/ToastNotification/ToastNotification.tsx
- src/interfaces/assistants_web/src/hooks/toast.ts
This pull request updates the `ToastNotification` component and the `useNotify` hook to improve the toast notifications.
- Removes the `Spinner` import.
- Updates the `cancelButtonStyle` to include an `accentColor` property.
- Modifies the `classNames` for the `cancelButton` and `error` toast types.
- Changes the `kind` and `fill` properties for the `info` icon.
- Removes the `info`, `success`, and `loading` functions.
> fix(toolkit): error toast notification

- src/interfaces/assistants_web/src/components/Agents/UpdateAgent.tsx
- src/interfaces/assistants_web/src/components/Shared/ToastNotification/ToastNotification.tsx
- src/interfaces/assistants_web/src/hooks/toast.ts
This pull request updates the `useNotify` hook and its usage in the `UpdateAgent` component. 
The `useNotify` hook now includes an `info` function, which displays an informational toast message with a duration of 5000. This change is reflected in the `UpdateAgent` component, where the use of the `success` function has been replaced with `info` to …
> add info toast back

- src/interfaces/assistants_web/package-lock.json
- src/interfaces/assistants_web/package.json
- src/interfaces/assistants_web/src/hooks/chat.ts
- src/interfaces/assistants_web/src/utils/citations.test.ts
- src/interfaces/assistants_web/src/utils/citations.ts
- src/interfaces/assistants_web/vitest.config.ts
- Adds test suit for testing assistants_web
- fix: when markdown image is fixed by replacing `! [` for `![` we don't carry over the extra blank space. Now its fixed
Closes TLK-1030
> test: add test suit

- src/backend/services/file.py
due to this additional check.
https://github.com/cohere-ai/cohere-toolkit/pull/602/files#diff-e938e72c3385f521a0f58fc519c9a42068c09e391d3c473f374ed00793a392c3R239-R241
> fix compass params

- src/interfaces/assistants_web/src/hooks/chat.ts
- src/interfaces/assistants_web/src/utils/citations.ts
https://github.com/cohere-ai/cohere-toolkit/pull/707/files#diff-9ff1b1bbfff26321f7875cd988ff9823fa990e7c5d4a39b6a4b8dca23959f0b5R40
This pull request updates the `citations.ts` file to address an issue with the current model consistently returning incorrect Markdown image syntax.
- Renames the `fixMarkdownImagesInText` function to `fixMarkdown` and …
> fix(toolkit): name not updated

- src/backend/routers/scim.py
- src/backend/schemas/scim.py
Change field names to snake case. Use naming strategy to transform to / from camelCase
> chore: snake case

- src/backend/tests/unit/chat/test_tool_calls.py
This pull request updates the import statement for the `MockCohereDeployment` module in the `test_tool_calls.py` file.
- `src/backend/tests/unit/chat/test_tool_calls.py`: Updates the import statement for `MockCohereDeployment` to include the `unit` package.
> Move test file

- src/backend/chat/custom/tool_calls.py
The `_call_tool_async` function in `tool_calls.py` has been updated to include additional logging and error handling when a custom chat tool is not included in the "tools" parameter.
- When a tool is not found in the `AVAILABLE_TOOLS`, the function now logs an info message with the event and error details.
- Instead of returning an empty list `[]`, the …
> Pass tool not available back to the model 

- src/interfaces/coral_web/package-lock.json
- src/interfaces/coral_web/package.json
> bump: update postcss 8.4.31 -> 8.4.39 in coral-web

- src/backend/tools/files.py
The pull request makes changes to the `call` async function in `src/backend/tools/files.py`. 
The function constructs a dictionary with keys `"text"`, `"title"`, and `"url"`. The value for the "url" key has been changed from `retrieved_file.file_path` to `retrieved_file.file_name`. This modification ensures that the URL is derived from the file name …
> remove file path in tools

- src/interfaces/assistants_web/src/components/SideNavPanel/ConversationCard.tsx
This pull request updates the `ConversationCard` component in the `SideNavPanel` of the assistants web interface. 
**Changes:**
- Increases the `gap-y` value in the `div` with class `flex flex-col` from `1` to `2`.
- Wraps the `name` text within a `Text` component with a `styleAs` prop set to `'p-sm' and a `className` prop set to `'truncate''.
- Adds a …
> feat(toolkit): update conversation card

- src/backend/config/configuration.template.yaml
- src/backend/config/secrets.template.yaml
- src/backend/config/settings.py
- src/backend/config/tools.py
- src/backend/schemas/agent.py
- src/backend/schemas/tool.py
- src/backend/tests/unit/factories/agent.py
- src/backend/tests/unit/factories/agent_tool_metadata.py
- src/backend/tools/__init__.py
- src/backend/tools/base.py
- src/backend/tools/brave_search/__init__.py
- src/backend/tools/brave_search/client.py
- src/backend/tools/brave_search/tool.py
- src/backend/tools/google_drive/auth.py
- src/backend/tools/google_search.py
- src/backend/tools/hybrid_search.py
- src/backend/tools/tavily_search.py
- src/backend/tools/utils/mixins.py
- src/backend/tools/web_scrape.py
- src/interfaces/assistants_web/src/constants/tools.ts
This PR introduces a new `hybrid_web_search` tool, which combines the capabilities of existing web search tools. The tool is designed to return a list of relevant document snippets for a given textual query, retrieved from the internet using a mix of existing web search tools.
The PR also makes the following changes:
- Adds the `hybrid_web_search` tool to the `src/backend/config/configuration.template.yaml` file.
- Adds the `hybrid_web_search` tool to the `src/backend/config/settings.py` file.
- Adds the `hybrid_web_search` tool to the `src/backend/config/tools.py` file.
- Adds the `hybrid_web_search` tool to the `__all__` list in `src/backend/tools/__init__.py` file.
- Adds the `hybrid_web_search` tool to the `src/interfaces/assistants_web/src/constants/tools.ts` file. …
> backend: Add Hybrid Search

- src/interfaces/assistants_web/src/components/Markdown/tags/Iframe.tsx
- src/interfaces/coral_web/src/components/Shared/Markdown/tags/Iframe.tsx
Add sandbox attribute to iframe component in order to prevent any malicious attack in a shared conversation
Closes TLK-1626
> security(ui): add sandbox attribute to iframe

- src/backend/Dockerfile
- src/interfaces/assistants_web/src/app/(auth)/login/Login.tsx
- src/interfaces/assistants_web/src/env.mjs
- src/interfaces/coral_web/src/env.mjs
- Add error to client web app when backend is not running
This pull request introduces several changes to the codebase, primarily focusing on the backend and interface components.
- The `src/backend/Dockerfile` file has been modified, commenting out the `CMD` command for the backend service. This change may indicate a temporary modification or a debugging step.
- The `src/interfaces/assistants_web/src/app/(auth)/login/Login.tsx` file has been updated, removing the `as="h1"` and `styleAs="h3"` attributes from the `<Text>` component. This change simplifies the component's markup.
- The `src/interfaces/assistants_web/src/env.mjs` and `src/interfaces/coral_web/src/env.mjs` files have been enhanced with a new `ServerError` class, which extends the `Error` class. This class …
> frontend: Add backend server error

- docs/custom_tool_guides/slack.md
- docs/custom_tool_guides/tool_guide.md
- src/backend/tools/base.py
This pull request introduces changes to the documentation and codebase, streamlining the process of adding and enabling custom tools.
- **docs/custom_tool_guides/tool_guide.md**:
- Provides a clear path for contributing custom tools to the main repository, emphasizing the use of the `community` folder.
- Offers flexibility for forked repos, allowing …
> docs: Improve tool docs & reflect current state

- aws_copilot_deploy/aws-api.Dockerfile
- azure_compose_deploy/azure-api.Dockerfile
- gcp.backend.Dockerfile
- src/backend/Dockerfile
- src/backend/debug.Dockerfile
Upgrade to Poetry 1.8.4
This PR updates the `poetry` version from `1.6.1` to `1.8.4` in the following Dockerfiles:
- `aws_copilot_deploy/aws-api.Dockerfile`
- `azure_compose_deploy/azure-api.Dockerfile`
- `gcp.backend.Dockerfile`
- `src/backend/Dockerfile`
- `src/backend/debug.Dockerfile`
> Upgrade to Poetry 1.8.4

- README.md
- docs/walkthrough/walkthrough.md
This pull request introduces several updates to the project's documentation, primarily focusing on the README.md and walkthrough.md files.
The changes aim to enhance the clarity and comprehensiveness of the project's documentation, ensuring that users have access to up-to-date information about the project's interfaces, backend API, and pre-built tools. …
> docs: More docs

- docs/custom_tool_guides/tool_guide.md
> docs: More tool docs to clarify tool addition

- src/interfaces/coral_web/next-env.d.ts
- src/interfaces/coral_web/package-lock.json
- src/interfaces/coral_web/package.json
This pull request updates the `next` dependency in the `package.json` and `package-lock.json` files from version `14.2.12` to `14.2.21`.
It also updates the `next` version in the `next-env.d.ts` file from `14.2.12` to `14.2.23`.
- Updates the `next` dependency in the `package.json` file from `14.2.12` to `14.2.21`.
- Updates the `next` dependency in the `package-lock.json` file from `14.2.12` to `14.2.21`.
- Updates the `next` version in the `next-env.d.ts` file from `14.2.12` to `14.2.23`.
> security: Update coral_web nextJS

- src/backend/crud/agent.py
- src/backend/crud/deployment.py
- src/backend/routers/agent.py
- Fixed the docstrings for CRUDs and routers
> docs: fix cruds and routers docstrings
