- Makefile
Removes docker command used in testing for docker images. Single container docker image is preferred
> chore: clean up makefile with defunct docker command

- README.md
We want to encourage people to use the docker single container image because it is faster and easier to pull. This PR updates the instructions to point to single container docker instead of backend and FE images
> Update readme to point to single container docker deploy

- src/interfaces/coral_web/src/components/Conversation/index.tsx
Only force enable file reader on message send if
- files exist in the conversation
- files don't exist in the conversation but a file has been uploaded in the message to be sent
> coral-web: Only force enable file reader on send if files exist in conversation

- README.md
While we're resolving issues with the one-click deployment, remove the button from the README
> tools: Hide the GCR one-click deploy button

- src/interfaces/coral_web/src/cohere-client/constants.ts
Updates the default chat tool value from `Wiki Retriever - LangChain` --> `Wikipedia` to match the backend.
This also fixes the issue of the `Chat with Wikipedia` start option not enabling the default chat tool when selected
> coral-web: Update wikipedia tool name

- docker_scripts/functions
- standalone.Dockerfile
- Use public Terrarium image for single.Docker(multistage build)
> Single Docker - use Terrarium public image

- src/interfaces/coral_web/src/components/Messages/Welcome/StartOptions.tsx
The composer wasn't being focused because the newly selected start option was focusing almost at the same time. A delay is added here to ensure the selected start option state settles before attempting to focus on the composer
https://github.com/cohere-ai/cohere-toolkit/assets/140425731/f0f73ce6-3866-4d1b-945c-04e1e831404d
> coral-web: Delay composer focus on Document start option select

- src/backend/routers/chat.py
- src/backend/schemas/chat.py
- src/backend/tools/function_tools/python_interpreter.py
This PR 
- fixes python interpreter using langchain. Currently tool use using Cohere API passes in a dictionary with a code key, but Langchain passes in code string as the parameter. This PR adds a langchain wrapper to call the function with the right parameters
- Fixes streaming of langchain by removing async
- Passes the results of the langchain events through to frontend 
- Sends a stream start event when the langchain Chat stream starts
https://github.com/cohere-ai/cohere-toolkit/assets/15705112/96b77b8c-2f70-46ea-a73c-eafec54508b8
> Langchain Chat Improvements

- src/backend/tests/routers/test_chat.py
- src/backend/tests/tools/retrieval/test_collate.py
- src/backend/tests/tools/retrieval/test_lang_chain.py
**Description:** cohere deployment is not required, so tests that depend on it should be skipped when the API key is not set
> Tests: skip when cohere api key is not set

- .github/workflows/backend_tests.yml
- src/backend/tests/routers/test_chat.py
- src/backend/tests/tools/retrieval/test_collate.py
- src/backend/tests/tools/retrieval/test_lang_chain.py
> Tests: fix skip tests

- src/interfaces/coral_web/src/cohere-client/client.ts
- src/interfaces/coral_web/src/cohere-client/generated/index.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/ChatResponseEvent.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/ManagedTool.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/StreamEnd.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/StreamToolCallsGeneration.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/StreamToolResult.ts
- src/interfaces/coral_web/src/cohere-client/generated/services/DefaultService.ts
- src/interfaces/coral_web/src/components/Citations/CitationDocument.tsx
- src/interfaces/coral_web/src/components/Citations/CitationTextHighlighter.tsx
- src/interfaces/coral_web/src/components/MarkdownImage.tsx
- src/interfaces/coral_web/src/components/MessageContent.tsx
- src/interfaces/coral_web/src/components/MessageRow.tsx
- src/interfaces/coral_web/src/components/ToolEvents.tsx
- src/interfaces/coral_web/src/constants.ts
- src/interfaces/coral_web/src/hooks/chat.ts
- src/interfaces/coral_web/src/hooks/streamChat.ts
- src/interfaces/coral_web/src/stores/index.ts
- src/interfaces/coral_web/src/stores/slices/citationsSlice.ts
- src/interfaces/coral_web/src/themes/cohereTheme.js
- src/interfaces/coral_web/src/types/message.ts
- src/interfaces/coral_web/src/utils/citations.ts
This PR adds support for rendering tool events sent from the langchain multihop chat endpoint, including adding the functionality to render images from the python interpreter in multihop mode.
**Tests:**
To test, add `USE_EXPERIMENTAL_LANGCHAIN=true` to your `.env` file. Then, select the `python_interpreter` and `internet search` tools and ask a query like `plot the 3 tallest mountains in the world`.
https://github.com/cohere-ai/cohere-toolkit/assets/5898755/bb1b0c5e-0734-4f9c-afe6-cb4f56110e46
> coral-web: support langchain multihop

- Makefile
- **Description:** Add a target to Makefile to stop all containers.
i'm not sure if using `stop -> docker compose down` is more appropriate compared to using `stop -> docker compose stop` and `down -> docker compose down`. please feel free to adjust according to community consensus and norms.
> deployment: add docker compose down command in Makefile.

- src/interfaces/coral_web/src/components/Configuration/Tools.tsx
- disables tools that have a false `is_available` value
- add tool `description` as tooltip, else  use `error_message`
> coral_web: Add is_available check to tools

- src/backend/models/database.py
> Setup: fix key error

- src/interfaces/coral_web/src/components/Conversation/index.tsx
File uploads were always creating a new conversation due to the conversation id being missing from the request. The PR adds the `conversation_id` to the file upload request
> coral-web: include conversationId in file upload

- src/backend/routers/conversation.py
- src/backend/routers/deployment.py
- src/backend/routers/tool.py
- src/interfaces/coral_web/.env.development
- src/interfaces/coral_web/next.config.mjs
- src/interfaces/coral_web/src/cohere-client/client.ts
Google Cloud Run only allows us to have one open port for the application. This means that if we want to run the backend and the frontend in the same container on GCR, the client won't be able to directly reach the backend and we'll need to proxy through the next.js application serving the frontend code.
This change adds a `rewrite` rule to the next.js config to allow for that proxying. The way this PR is written now, all API requests would be changed to route through next.js, though it would be possible to make that configurable to skip a hop.
> backend: Set up next.js to proxy requests to the API

- .env-template
- README.md
- src/backend/cli/main.py
With the new routing of API requests through next.js, we need to update the default `NEXT_PUBLIC_API_HOSTNAME` value set in the `.env` file when running setup.
> tools: Update default NEXT_PUBLIC_API_HOSTNAME for the new api routing

- .github/actions/js-install/actions.yml
- .github/workflows/interface_tests.yml
Adds build and lint check workflow for `coral_web`
> github actions: add build + lint check workflow for coral_web 

- src/backend/model_deployments/cohere_platform.py
- **Description:** Backend failed to start due to missing field in API response for listing models. See details:
Logs:
```
...
INFO:     Finished server process [46]
Process SpawnProcess-5:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/workspace/.venv/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
target(sockets=sockets)
File "/workspace/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 62, in run
return asyncio.run(self.serve(sockets=sockets))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
> fix: missing field in api response causing backend failure

- src/backend/main.py
- src/backend/services/logger.py
Adds a simple logging middleware to Fast API app. 
Tested locally
> backend: add basic logging middleware

- src/community/config/tools.py
- src/community/tests/tools/functions/test_clinicaltrials.py
- src/community/tools/function_tools/__init__.py
- src/community/tools/function_tools/clinicaltrials.py
Enables clinical studies to be retrieved from ClinicalTrials.gov, with optional filtering by condition, location, intervention, and recruiting status.
Three unrelated tests are failing locally for me:
```
FAILED src/backend/tests/routers/test_deployment.py::test_list_deployments_has_all_option[mock_available_model_deployments0] - AssertionError: assert 5 == 3
FAILED src/backend/tests/routers/test_deployment.py::test_list_deployments_no_available_models_404[mock_available_model_deployments0] - assert 200 == 404
FAILED src/backend/tests/routers/test_deployment.py::test_list_deployments_no_available_models_with_all_option[mock_available_model_deployments0] - AssertionError: assert 5 == 3
```
> tools: add ClinicalTrials.gov API as function tool

- src/backend/cli/main.py
When we removed the proxy from the frontend, we didn't update the CLI setup script to use `localhost:8000` as the default backend instead of `backend:8000`.
This pull request updates the `NEXT_PUBLIC_API_HOSTNAME_DEFAULT` in the `main.py` file.
The pull request updates the `NEXT_PUBLIC_API_HOSTNAME_DEFAULT` variable in the `main.py` file to use "http://localhost:8000" as the default API hostname instead of "http://backend:8000".
- Updates `NEXT_PUBLIC_API_HOSTNAME_DEFAULT` to "http://localhost:8000".
> tools: Update default API hostname to localhost:8000

- src/interfaces/coral_web/src/components/DeploymentsDropdown.tsx
Adds a missing check for `deployment` being `undefined` with the `DeploymentsDropdown.tsx`. In reality, this should never be `undefined` since the dropdown is filled in by the `allDeployments` endpoint.
This pull request makes changes to the `DeploymentsDropdown` component in the `src/interfaces/coral_web/src/components/DeploymentsDropdown.tsx` file. 
The pull request removes the `useState` import from 'react' and updates the condition check inside the `DeploymentsDropdown` functional component.
- Removed `useState` from imports.
- Updated the condition check inside the `DeploymentsDropdown` function to include an additional check for `deployment`. Now, it checks if `deployment` exists and if it's not available (`!deployment.is_available`).
> coral-web: fix deployments dropdown  check

- Makefile
- docs/setup.md
-  Documentation improvements
The PR introduces Windows-specific setup and first-run instructions for the project. 
**Changes:**
- Added `win-setup` and `win-first-run` targets to the `Makefile`.
- Updated the `docs/setup.md` file to include detailed Windows setup instructions.
- Modified the commands for installing Scoop, Poetry, and Miniconda to use specific versions and adjusted the `conda init` command.
- Added a section for possible issues during installation, providing troubleshooting steps for errors related to `llama-cpp-python`.
> Improvements to Windows setup documentation

- docs/service_deployments.md
-  Small fix to the documentation
This pull request updates the documentation for deploying the Toolkit to Azure Cloud App. 
The `docs/service_deployments.md` file has been updated to reflect changes in the deployment process of the Toolkit to the Microsoft Azure Platform. 
- Updated the link in the "Deploying to Azure Cloud App" section to point to the `main` branch instead of the `eugene/EXT2-69_azure_hpa` branch.
- Added a note mentioning that this deployment type uses Azure Container App to host the Toolkit.
- Updated the deployment steps to include selecting or creating a resource group and entering a specific connection string format.
> Azure Container App one click deployment

- src/backend/config/tools.py
- src/backend/tests/tools/test_calculator.py
- src/backend/tools/calculator.py
- Fix calculator citations not working by renaming the output field to `text` instead of `result`
- Improve calculator description for better input generations
- Strip comments and new lines from generated expression to avoid parsing issues
The pull request makes changes to the calculator tool's functionality and description. 
The calculator tool has been enhanced to offer a wider range of mathematical and conversion capabilities. The tool's description has been updated to reflect its expanded capabilities, including a large library of customizable functions, unit and currency conversions, and symbolic calculations. 
- The `code` parameter's description has been updated to specify that it should be a "valid mathematical expression" for the calculator to evaluate. 
- The …
> Tool: improve calculator

- .github/workflows/check_revision_id.yml
- docs/troubleshooting.md
This pull request updates the workflow to check for duplicate revision IDs and adds troubleshooting documentation for an Alembic error.
- Updated the `paths` for both `pull_request` and `push` events in the `check_revision_id.yml` workflow to include all files in the `src/backend/alembic/versions/` directory.
- Added a new section in `troubleshooting.md` to address an Alembic error that may occur when running the `make migrate` command. The section provides a solution by suggesting additional commands to run before rerunning the `make migrate` command.
> Docs: add alembic troubleshooting

- poetry.lock
- pyproject.toml
- src/backend/schemas/chat.py
- src/backend/services/chat.py
- src/backend/tests/model_deployments/mock_deployments/mock_azure.py
- src/backend/tests/model_deployments/mock_deployments/mock_bedrock.py
- src/backend/tests/model_deployments/mock_deployments/mock_cohere_platform.py
- src/backend/tests/model_deployments/mock_deployments/mock_sagemaker.py
- src/community/model_deployments/hugging_face.py
- src/community/model_deployments/local_model.py
With the new version of the Cohere SDK, chat_history can contain tool results, which was breaking existing tests
The PR introduces a new `TOOL` role for `ChatRole` in the `Chat` module. This change affects both the schema definition in `chat.py` and the `generate_chat_response` function in `services/chat.py`.
**Files changed:**
- `src/backend/schemas/chat.py`
- `src/backend/services/chat.py`
**Code changes:**
- Added a new `TOOL` role to the `ChatRole` `StrEnum` in `chat.py`.
- Modified the `ChatMessage` class in `chat.py` to include an optional `tool_results` field, which stores a list of tool call results.
- Updated the default value of the `tool_results` field in `chat.py` to an empty list.
- Refactored the `generate_chat_response` function in `services/chat.py` to …
> Chat: update response

- src/interfaces/coral_web/package-lock.json
- src/interfaces/coral_web/package.json
- src/interfaces/coral_web/src/components/MessageContent.tsx
- src/interfaces/coral_web/src/components/Shared/Markdown/Markdown.tsx
- src/interfaces/coral_web/src/components/Shared/Markdown/tags/Iframe.tsx
- src/interfaces/coral_web/src/utils/preview.ts
Adds preview to `Pre` component to render HTML blocks using iframes
- Issue: OS-1985
- Dependencies: No dependencies
This pull request introduces a new feature that allows users to include code blocks in their messages, which will be displayed as interactive iframes. 
**Changes include:**
- New utility functions `addOnErrorToImg` and `getReconstructedHtml` in `preview.ts` to process and reconstruct HTML from a plain string.
- New `Iframe` component in `Iframe.tsx` that renders an iframe with a lazy loading mechanism. It also includes a `SyntaxHighlighter` to style the code.
- Updates to `package.json` and `package-lock.json` to include new dependencies required for the new feature.
- Modifications to `MessageContent.tsx` to incorporate the `isFulfilledMessage` type and …
> frontend: adds preview to html code snippets

- src/interfaces/coral_web/src/components/EditEnvVariablesButton.tsx
- src/interfaces/coral_web/src/components/Layout.tsx
Changes default page head title from Coral --> Chat
This pull request makes changes to two component files in the `src/interfaces/coral_web/src/components` directory:
- `EditEnvVariablesModal.tsx`: The component now expects an additional prop, `defaultDeployment` of type `string`. This prop is used to initialize the `deployment` state.
- `Layout.tsx`: The default value of the `title` prop has been changed from `'Coral'` to `'Chat''.
The pull request updates the `EditEnvVariablesModal` and `Layout` components in the `coral_web` interface. The `EditEnvVariablesModal` component now expects a `defaultDeployment` prop, which is used to set the initial value of the `deployment` state. This change allows for more flexible usage of the component by providing a way to preset the …
> coral-web: Change default page head title from Coral --> Chat

- src/backend/database_models/agent.py
- src/backend/schemas/agent.py
- src/backend/tests/crud/test_agent.py
- src/backend/tests/factories/agent.py
- src/backend/tests/routers/test_agent.py
- src/interfaces/coral_web/src/cohere-client/generated/index.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/Agent.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/AgentDeployment.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/AgentModel.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/Auth.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/ChatMessage.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/ChatRole.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/CohereChatRequest.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/CreateAgent.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/DeleteAgent.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/Login.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/NonStreamedChatResponse.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/StreamCitationGeneration.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/StreamQueryGeneration.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/StreamSearchQueriesGeneration.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/StreamSearchResults.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/StreamStart.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/StreamToolCallsGeneration.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/StreamToolInput.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/StreamToolResult.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/UpdateAgent.ts
- src/interfaces/coral_web/src/cohere-client/generated/services/DefaultService.ts
- src/interfaces/coral_web/src/components/EditEnvVariablesButton.tsx
- rename enums here https://github.com/cohere-ai/cohere-toolkit/pull/189/files#diff-e8df845c69e9e2f234328ef155343e0603899cf22aa220a876a1c30362330debR6 to avoid naming conflicts during client generation. (deployment.ts is already a generated client file)
- ran `pnpm generate:client` and `pnpm format:write`
This PR introduces the `Agent` model and related changes. 
The `Agent` model is defined with the following fields:
- `user_id`: A string.
- `id`: A string.
- `created_at`: A string.
- `updated_at`: A …
> [coral-web] rename schema fields and update openapi client

- .env-template
- src/backend/routers/experimental_features.py
Adds a variable to use the agents view to be consumed in the front end.
Closes OS-2076
This PR introduces a new experimental feature flag `USE_AGENTS_VIEW` and updates the code to handle this new feature.
- Adds `USE_AGENTS_VIEW=False` to the list of experimental features in the `.env-template` file.
- Updates the `list_experimental_features` function in `experimental_features.py` to include the new feature flag.
> Add use agents view env variable. 

- src/interfaces/coral_web/src/components/Shared/Markdown/directives/cite.ts
- src/interfaces/coral_web/src/components/Shared/Markdown/tags/Iframe.tsx
- src/interfaces/coral_web/src/hooks/chat.ts
- src/interfaces/coral_web/src/pages/c/[id]/index.tsx
- src/interfaces/coral_web/src/utils/citations.ts
- src/interfaces/coral_web/src/utils/conversation.ts
Fix inline citations in code blocks
- New logic for `replaceTextWithCitations`. If a citation start index is greater than the length of the `replacedText` it will be added at the top(1) of the message as shown in the picture. 
[1] I couldn't make it work at the bottom, looks like remark/rehype takes the whole text as `html` instead of `html` + `markdown`
> fix: html preview with citations

- src/interfaces/coral_web/src/components/MessageContent.tsx
This pull request makes changes to the `MessageContent` component in the `src/interfaces/coral_web/src/components/MessageContent.tsx` file. 
The `MessageContent` component is updated to wrap its content in a `div` element when the `hasLoadingMessage` prop is `true`. This is achieved by adding an `as="div"` prop to the `Transition` element within the …
> coral-web: add missing 'as' prop to transition component

- src/backend/crud/conversation.py
- src/backend/tests/crud/test_conversation.py
Listing conversations did not return the most recent ones, giving the impression that conversations were not persisted.
The `get_conversations` function in `conversation.py` has been updated to sort conversations by their creation date in descending order. This ensures that the most recently created conversations are retrieved first.
- The `.order_by(Conversation.created_at.desc())` line has been added to the `get_conversations` function, specifying the sorting order.
> Conversations: fix list conversations

- docs/custom_tool_guides/tool_guide.md
- docs/how_to_guides.md
- src/backend/cli/main.py
This PR updates the API endpoint paths in the documentation and the `main.py` file. 
The changes include:
- Updating the API endpoint paths by adding `/v1` before the specific endpoint, such as `/tools`, `/chat-stream`, and `/langchain-chat`.
- Modifying the example commands to use the updated API endpoint paths, ensuring consistency and accuracy in the documentation.
> Add v1 to docs

- src/backend/services/chat.py
The `process_chat` function in `chat.py` has been modified to include an additional check before attaching files to messages. 
- Previously, the code directly called the `attach_files_to_messages` function to attach files to the chat session. 
- Now, an `if should_store:` condition has been added to control whether files are attached to messages. 
This change allows for more flexibility in handling file attachments, potentially based on specific conditions or user preferences.
> Propagate should_store logic to the File upload logic

- src/backend/config/tools.py
- src/backend/schemas/tool.py
- src/community/config/tools.py
- src/interfaces/coral_web/src/cohere-client/generated/models/ManagedTool.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/Tool.ts
- src/interfaces/coral_web/src/cohere-client/generated/services/DefaultService.ts
- src/interfaces/coral_web/src/components/Configuration/Tools.tsx
Add display name for tools 
This pull request updates the naming convention for tool names and adds a new field, `display_name`, to the `Tool` and `ManagedTool` interfaces.
- The tool names in `ToolName` and `CommunityToolName` enums have been changed to use snake_case instead of camelCase.
- A new field, `display_name`, has been added to the `Tool` and `ManagedTool` interfaces in `tool.py, `Tool.ts`, and `ManagedTool.ts`.
- The `ToolSection` component in `Tools.tsx` has been updated to use the `display_name` field instead of the `name` field for rendering tool labels.
- The `display_name` field has been added to the `ToolName` and `CommunityToolName` enums in `tools.py` and `config/tools.py`.
> Split up display name and name for Tools 

- src/interfaces/coral_web/src/components/Conversation/index.tsx
`isEditAgentPanelOpen` was being set to `undefined` by the persisted store (?) after app mount
This was causing the agent info panel to show on page load
https://github.com/cohere-ai/cohere-toolkit/assets/140425731/fe972bfc-9d88-4c17-add3-3aa83a4decd9
https://github.com/cohere-ai/cohere-toolkit/assets/140425731/8c495945-30e0-4c6b-b083-a0dd669d41b8
> coral-web: fix agent info panel opening by default

- src/backend/config/routers.py
- src/backend/routers/agent.py
- src/backend/services/request_validators.py
- src/backend/tests/routers/test_agent.py
Only allow creator of agent to update the agent.
in this PR:
- Update some HTTP codes to be more accurate to the actual error
- Update minor string formatting for errors to be more consistent
- Update the validator for update agent request to cross check the user ID is the creator of the agent
- Update unit tests
This pull request makes changes to the backend code, specifically related to agent management and validation. 
**Summary:**
- Updates the `status_code` from `404` to `400` for more accurate error handling when an agent is not found.
- Enhances the `validate_update_agent_request` function to include additional checks for the agent ID and user ID, ensuring requests are properly validated.
- Adjusts test cases to reflect the updated status codes and error …
> [backend] enforce agent update with user-id

- src/interfaces/coral_web/src/components/Agents/CreateAgentForm.tsx
- src/interfaces/coral_web/src/components/Agents/UpdateAgentPanel.tsx
Improvements to UX
| before | after |
| - | - |
| <video src="https://github.com/cohere-ai/cohere-toolkit/assets/19353218/e3c77ed7-0ac2-4872-90dc-3a3ec8875628" /> | <video src="https://github.com/cohere-ai/cohere-toolkit/assets/19353218/d88cc06f-40a9-4441-abd7-a34988da96f9" /> |
| <video src="https://github.com/cohere-ai/cohere-toolkit/assets/19353218/b1bcb38b-b440-4685-9211-627647b4b5aa" /> | <video src="https://github.com/cohere-ai/cohere-toolkit/assets/19353218/150dce33-14e4-43e8-83ae-5b3477c70a34" /> |
This pull request makes changes to two files in the `src/interfaces/coral_web/src/components/Agents` directory:
- `CreateAgentForm.tsx**: Modifications are made to the layout and styling of the form used to create a …
> fix(toolkit): UX/UI improvements

- docs/troubleshooting.md
Add error troubleshooting
This PR adds troubleshooting steps for an error that occurs when the requested image's platform (`linux/amd64`) doesn't match the detected host platform (`linux/arm64/v8`). 
To resolve this issue, the following changes are made:
- A new section titled "Error: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested" is added to the `docs/troubleshooting.md` file.
- It is suggested to add `platform: linux/amd64` to the `docker_compose.yml` file, with an example configuration provided.
These changes will help users troubleshoot and resolve the specific error by providing clear instructions and an example configuration.
> Add error troubleshooting

- src/backend/config/tools.py
- src/backend/services/chat.py
- src/backend/tests/routers/test_chat.py
previously the tools were just overwritten with all of the tools in the agent
now, we dont overwrite them but rather check if the tools selected are assigned to the agent
also fixing renaming of tools to not clash with cohere platform API tools.
This pull request makes changes to the tool names and adds a test for tool validation.
- Renames `Python_Interpreter` to `toolkit_python_interpreter` and `Tavily_Internet_Search` to `web_search` in `src/backend/config/tools.py`.
- Adds validation to check if tools in the `chat_request` are present in the agent's tools in `src/backend/services/chat.py`.
- Adds a test `test_streaming_chat_with_tools_not_in_agent_tools` to verify the behavior when tools in the chat request are not present in the agent's tools in …
> [backend] agent chat fixes

- src/interfaces/coral_web/src/cohere-client/client.ts
- src/interfaces/coral_web/src/hooks/chat.ts
- src/interfaces/coral_web/src/hooks/streamChat.ts
https://github.com/cohere-ai/cohere-toolkit/assets/140425731/e145c1da-67d0-47ae-a227-f110753eeae0
This pull request introduces changes to the `src/interfaces/coral_web/src` module, specifically the `client.ts`, `chat.ts`, and `streamChat.ts` files. 
The changes are related to adding an `agentId` parameter to the `CohereClient` class and updating …
> coral-web: adds agent id to chat request

- helper_scripts/metrics_helper.py
- src/backend/routers/agent.py
- src/backend/routers/user.py
- src/backend/schemas/metrics.py
- src/backend/services/metrics.py
This PR introduces a new helper script, `metrics_helper.py`, which contains functions for interacting with the Cohere Platform's user, agent, and conversation management endpoints. It also includes updates to the backend code related to user and agent management, and modifications to the metrics middleware and reporting functionality.
A new helper …
> metrics: add debug capabilities

- src/interfaces/coral_web/src/components/Agents/AgentCard.tsx
- src/interfaces/coral_web/src/components/Agents/AgentsList.tsx
- src/interfaces/coral_web/src/components/Agents/AgentsSidePanel.tsx
- src/interfaces/coral_web/src/components/Agents/CreateAgentForm.tsx
- src/interfaces/coral_web/src/components/Agents/DiscoverAgentCard.tsx
- src/interfaces/coral_web/src/components/Agents/Layout.tsx
- src/interfaces/coral_web/src/components/Agents/MobileHeader.tsx
- src/interfaces/coral_web/src/components/Agents/Settings/FilesTab.tsx
- src/interfaces/coral_web/src/components/Agents/Settings/SettingsDrawer.tsx
- src/interfaces/coral_web/src/components/Agents/Settings/ToolsInfoBox.tsx
- src/interfaces/coral_web/src/components/Agents/Settings/ToolsTab.tsx
- src/interfaces/coral_web/src/components/Agents/UpdateAgentPanel.tsx
- src/interfaces/coral_web/src/components/Conversation/Header.tsx
- src/interfaces/coral_web/src/components/Conversation/MessagingContainer.tsx
- src/interfaces/coral_web/src/components/Conversation/index.tsx
- src/interfaces/coral_web/src/constants.ts
- src/interfaces/coral_web/src/hooks/agents.ts
- src/interfaces/coral_web/src/stores/index.ts
- src/interfaces/coral_web/src/stores/persistedStore.ts
- src/interfaces/coral_web/src/stores/slices/agentsSlice.ts
- src/interfaces/coral_web/src/stores/slices/settingsSlice.ts
This PR makes changes to the Agents component, including:
- Renaming `isAgentsSidePanelOpen` to `isAgentsSidePanel` in `AgentsList.tsx` and `AgentsSidePanel.tsx`.
- Replacing `useSettingsStore` with `useAgentsStore` in `AgentsList.tsx`, `AgentsSidePanel.tsx`, `MobileHeader.tsx`, and `Settings/SettingsDrawer.tsx`.
- Adding `useRecentAgents` from '@/hooks/agents'` in `AgentCard.tsx`, `CreateAgentForm.tsx`, and `DiscoverAgentCard.tsx`.
- Replacing `useAgentsStore` with `useRecentAgents` in `AgentCard.tsx`.
- Replacing `useAgentsStore` with `useSettingsStore` in `UpdateAgentPanel.tsx`.
- Adding `useAgentsStore` in `Conversation/index.tsx` and `Conversation/MessagingContainer.tsx`.
- Replacing `useSettingsStore` with `useAgentsStore` in `Conversation/Header.tsx`.
- Adding …
> fix(toolkit): remove settings tab and fixes bug

- src/backend/schemas/metrics.py
- src/backend/services/metrics.py
This pull request updates the `MetricsDataBase` class in the module to include a new field, `secret`, which is assigned the value `"secret"`. This change is reflected in both the `src/backend/schemas/metrics.py` and `src/backend/services/metrics.py` files.
Additionally, the following modifications are made:
- The `REPORT_SECRET` environment variable is …
> metrics: configure secrets

- src/interfaces/coral_web/src/components/Agents/Settings/SettingsDrawer.tsx
- src/interfaces/coral_web/src/components/Conversation/index.tsx
- src/interfaces/coral_web/src/components/Settings/SettingsDrawer.tsx
- src/interfaces/coral_web/src/hooks/chat.ts
This pull request makes changes to the `SettingsDrawer` and `Conversation` components in the `coral_web` interface, and also updates the `chat.ts` file. 
- The `SettingsDrawer` component in `SettingsDrawer.tsx` has been modified to include a `key` prop for each tab's `div` element, ensuring a unique identifier for efficient React rendering and reconciliation.
- The `Conversation` component in `index.tsx` now includes the `resetConversation` property from the `useConversationStore` hook. It also updates the `useRouteChange` hook to invoke `resetConversation` when the route changes.
- The `chat.ts` file has removed the `useRouter` import from 'next/router' and the associated usage of `useRouter` in the `useChat` function.
- The `tabs.map` function now returns a `div` …
> coral-web: reset conversation on route change

- src/interfaces/coral_web/src/components/Agents/Settings/SettingsDrawer.tsx
This pull request makes changes to the rendering of tabs in the `SettingsDrawer` component. 
The `SettingsDrawer` component now conditionally renders its content based on the length of the `tabs` array. If there is only one tab, it is rendered directly within a `div`, without the wrapping `Tabs` component. When there are multiple tabs, the existing behavior of rendering each tab within the `Tabs` component remains unchanged.
- The code now checks the length of the `tabs` array before rendering its content.
- If there is only one tab, it is rendered within a `div` with the class name "pt-5".
- For multiple tabs, the existing rendering logic within the `Tabs` component is retained.
> coral-web: remove tab header in config drawer when only 1 tab is available

- src/interfaces/coral_web/src/cohere-client/client.ts
- src/interfaces/coral_web/src/components/Agents/Settings/SettingsDrawer.tsx
- src/interfaces/coral_web/src/components/Agents/Settings/ToolsTab.tsx
- src/interfaces/coral_web/src/components/Citations/CitationDocumentHeader.tsx
- src/interfaces/coral_web/src/components/Conversation/Composer/ComposerToolbar.tsx
- src/interfaces/coral_web/src/components/Conversation/Composer/EnabledDataSources.tsx
- src/interfaces/coral_web/src/components/Conversation/Composer/index.tsx
- src/interfaces/coral_web/src/components/Conversation/index.tsx
- src/interfaces/coral_web/src/components/Settings/SettingsDrawer.tsx
- src/interfaces/coral_web/src/components/Settings/ToolsTab.tsx
- src/interfaces/coral_web/src/components/Shared/Markdown/Markdown.tsx
- src/interfaces/coral_web/src/components/ToggleCard.tsx
- src/interfaces/coral_web/src/hooks/chat.ts
- src/interfaces/coral_web/src/pages/agents/[[...slug]].tsx
Use `tools` given by the `/agent` api to show tools specific to that agent. Also removes the ability to deselect tools from the composer if we are using the non-base agent.
https://github.com/cohere-ai/cohere-toolkit/assets/5898755/d3ceec49-6135-4fe1-bfe7-093deb506f20
This PR introduces changes to the settings drawer and tools tab in the user interface. It also updates the `CohereClient` class to use the new `ManagedTool` type.
- The `SettingsDrawer` component now uses the `useAgent` hook to fetch the agent data and dynamically render the tools tab based on the available tools.
- The `ToolsTab` component now accepts an optional `requiredTools` prop, allowing for more flexible rendering of available and unavailable tools.
- The `ComposerToolbar` and …
> coral-web: load tools from agent api

- src/interfaces/coral_web/src/components/Agents/UpdateAgentPanel.tsx
Save some vertical space on mobile and still ensure the user sees the info banner when the update panel is opened
https://github.com/cohere-ai/cohere-toolkit/assets/140425731/6cee9e13-a381-4528-846d-d6fcae828b25
https://github.com/cohere-ai/cohere-toolkit/assets/140425731/3daebacf-908d-431e-acf5-5bf7d377cdee
This pull request makes changes to the `UpdateAgentPanel` component in the `src/interfaces/coral_web/src/components/Agents/UpdateAgentPanel.tsx` file. 
The `UpdateAgentPanel` component now includes an `InfoBanner` displaying a message that updating the agent will impact all assistant users. This message was previously displayed using a `Banner` component. 
- Adds an `InfoBanner` component to display the message about the impact of agent updates.
- Updates the …
> coral-web: move update agent info banner above form on mobile

- src/interfaces/coral_web/src/components/Agents/Settings/ToolsTab.tsx
- src/interfaces/coral_web/src/components/Conversation/index.tsx
https://github.com/cohere-ai/cohere-toolkit/assets/140425731/fb658268-eeea-4cff-96f5-9b6ad93d334e
This pull request updates the `ToolsTab` component in the `src/interfaces/coral_web/src/components/Agents/Settings` directory. 
The changes in this PR aim to enhance the `ToolsTab` component by importing additional hooks and updating the component's logic to display tool information more effectively. 
- **New Imports**: 
- `useAgent` hook from `'@/hooks/agents'.
- `useSlugRoutes` hook from `'@/hooks/slugRoutes'.
- **Updated Logic**: 
- The component now uses the `agentId` from the `useSlugRoutes` hook to retrieve agent data using the `useAgent` hook.
- The tool information displayed now includes a conditional check to show a message if the agent does not use any tools.
> coral-web: show no tools message for agents who use 0 tools

- src/interfaces/coral_web/src/components/Conversation/Composer/ComposerToolbar.tsx
- src/interfaces/coral_web/src/components/Conversation/Composer/DataSourceMenu.tsx
- src/interfaces/coral_web/src/components/Conversation/Composer/EnabledDataSources.tsx
- src/interfaces/coral_web/src/components/Conversation/Composer/ListboxOptions.tsx
- src/interfaces/coral_web/src/components/Conversation/Composer/WebSearchConfigurationModal.tsx
- src/interfaces/coral_web/src/components/Conversation/Composer/index.tsx
- src/interfaces/coral_web/src/components/Conversation/index.tsx
- src/interfaces/coral_web/src/components/IconButton.tsx
- src/interfaces/coral_web/src/hooks/files.ts
- src/interfaces/coral_web/src/hooks/tags.tsx
Adds composer actions for data source options (tools and files) triggered by the `@` symbol. 
https://github.com/cohere-ai/cohere-toolkit/assets/5898755/86951e22-263a-49c2-a26e-cf1c315d0eb6
This PR introduces a new component, `DataSourceMenu`, and makes changes to the `ComposerToolbar` and `EnabledDataSources` components.
A new component, `DataSourceMenu`, has been added to display a list of available tools and data sources that the user can select from. It uses the TagType enum to differentiate between tools and files.
- The `DataSourceMenu` component has been added to `ComposerToolbar`.
- The `ToolbarActionButton` component has been replaced with the `IconButton` component.
- The `canDisableDataSources` prop has been removed and replaced with …
> coral-web: add composer @ actions

- src/interfaces/coral_web/src/components/Conversation/index.tsx
**Description:** 
Adds a missing import causing the frontend to be upset.
This pull request updates the import statements in `index.tsx` within the `Conversation` component of the `coral_web` interface.
The `useAgent` hook is now imported from `'@/hooks/agents'. This hook is likely used to manage the state and behavior of an agent or user within a conversation.
- Added `import { useAgent, ... } from '@/hooks/agents';` in `src/interfaces/coral_web/src/components/Conversation/index.tsx`.
> coral-web: import useAgent

- src/interfaces/coral_web/src/components/DataTable.tsx
- src/interfaces/coral_web/src/components/Shared/Markdown/Markdown.tsx
- src/interfaces/coral_web/src/components/Shared/Markdown/directives/table-tools.ts
- src/interfaces/coral_web/src/components/Shared/Markdown/directives/utils.ts
- src/interfaces/coral_web/src/utils/preview.ts
Enables iframe rendering with `rehype-raw`
- Fix: download CSV from the table (now the plugin points to HTML elements and not markdown anymore)
- Fix: extra blank spaces in front of the table
Closes OS-2196
> frontend: fix iframe preview with rehype-raw plugin

- src/interfaces/coral_web/src/components/Citations/CitationDocumentHeader.tsx
- src/interfaces/coral_web/src/components/FirstTurnSuggestions.tsx
- src/interfaces/coral_web/src/components/MessageRow.tsx
- src/interfaces/coral_web/src/components/ToolEvents.tsx
- src/interfaces/coral_web/src/constants.ts
- src/interfaces/coral_web/src/hooks/chat.ts
- src/interfaces/coral_web/src/types/message.ts
**Description:** 
This PR shows the tool events streaming in when using multihop. It also updates some tool names to match what the backend gives us.
Note: the stream response doesn't complete, likely due to my local setup being a bit broken but this demonstrates parsing the tool events streaming in:
https://github.com/cohere-ai/cohere-toolkit/assets/5898755/e659cb09-588d-470c-a840-75272aee25c4
This PR updates the code to replace references to `TOOL_INTERNET_SEARCH_ID` with `TOOL_WEB_SEARCH_ID`. This includes changes in the following files:
- `src/interfaces/coral_web/src/components/Citations/CitationDocumentHeader.tsx`
- `src/interfaces/coral_web/src/components/FirstTurnSuggestions.tsx`
- `src/interfaces/coral_web/src/components/ToolEvents.tsx`
- …
> coral-web: support multihop tool streaming events

- src/interfaces/coral_web/src/components/Agents/DiscoverAgentCard.tsx
Word breaks were happening within words, causing the descriptions to look funky.
|1|2|
|-|-|
|<img width="657" alt="Screenshot 2024-06-27 at 2 31 26 PM" src="https://github.com/cohere-ai/cohere-toolkit/assets/5898755/f29a7a2b-bc1f-46f6-8f8a-375de04e418a">|<img width="509" alt="Screenshot 2024-06-27 at 2 31 33 PM" src="https://github.com/cohere-ai/cohere-toolkit/assets/5898755/c94de5c2-ac6b-4143-a80e-27fd91f0db4c">|
This pull request makes changes to the `DiscoverAgentCard` component in the `src/interfaces/coral_web/src/components/Agents/` directory.
**Summary**
The PR removes the `break-all` CSS property from the `Text` element displaying the `description` prop of the `DiscoverAgentCard` component.
**Changes**
- Remove the `break-all` CSS property from …
> coral-web: fix partial word breaks in agent cards

- src/interfaces/coral_web/src/components/Agents/AgentForm.tsx
- src/interfaces/coral_web/src/components/Agents/CreateAgentForm.tsx
- src/interfaces/coral_web/src/constants.ts
https://github.com/cohere-ai/cohere-toolkit/assets/140425731/bf60b873-46c8-4688-bf5a-da66c75f30c6
This pull request updates the `CreateAgentForm` and `AgentForm` components to include new constants for tool IDs and default field values.
The `CreateAgentForm` and `AgentForm` components have been updated to include the `TOOL_READ_DOCUMENT_ID` and …
> coral-web: preselect + hide read_document and search_file tools in agent form

- src/interfaces/coral_web/src/pages/login.tsx
|after|before|
|-|-|
|<img width="931" alt="Screenshot 2024-06-27 at 2 51 02 PM" src="https://github.com/cohere-ai/cohere-toolkit/assets/5898755/8cd08644-bd2b-482f-95fa-54a119f8d94b">|<img width="933" alt="Screenshot 2024-06-27 at 2 51 19 PM" src="https://github.com/cohere-ai/cohere-toolkit/assets/5898755/593da055-2633-4eab-86f7-dd61baeb4924">|
This pull request makes changes to the `LoginPage` component in the `login.tsx` file. 
The `LoginPage` component has been updated to remove the "New user?" text and the associated `AuthLink` element. This change simplifies the login page by removing the explicit mention of user registration during the login process. 
- The `navigationAction` prop in the `WelcomePage` component has been removed, eliminating the …
> coral-web: remove register buttons on login screen

- src/interfaces/coral_web/src/components/Agents/AgentForm.tsx
- src/interfaces/coral_web/src/components/Agents/AgentToolFielPicker.tsx
- src/interfaces/coral_web/src/components/Agents/CreateAgent.tsx
- src/interfaces/coral_web/src/components/Agents/UpdateAgent.tsx
- src/interfaces/coral_web/src/components/Conversation/index.tsx
- src/interfaces/coral_web/src/pages/new.tsx
- src/interfaces/coral_web/src/types/tools.ts
This PR updates the code for creating and updating agents. It introduces a new type, `GoogleDriveToolArtifact`, and makes changes to the `AgentForm`, `AgentToolFielPicker`, `CreateAgent`, and `UpdateAgent` components.
- Renames `CreateAgentForm` to `CreateAgent` and updates the import statement for `AgentForm` and `AgentFormFields`.
- Removes the …
> chore(toolkit): cleanup and improve code for google drive file picker

- src/backend/chat/collate.py
- src/backend/tests/crud/test_agent_tool_metadata.py
- src/backend/tests/tools/test_collate.py
- Decrease rerank threshold
- Fix agent metadata tests
This PR makes changes to the `src/backend` directory, affecting the `chat`, `tests/crud`, and `tests/tools` modules. 
- Updates the `RELEVANCE_THRESHOLD` constant in `collate.py` from `0.3` to `0.1`.
- Refactors the `artifacts` and `type` attributes in `test_agent_tool_metadata.py` to use a dictionary format instead of a list.
- Adds an additional output to the `test_rerank` function in `test_collate.py`.
- Updates the `RELEVANCE_THRESHOLD` constant from `0.3` to `0.1`.
- Refactors the `artifacts` attribute in the `AgentToolMetadata` class to use a dictionary format, e.g., `artifacts=["file_id"]` becomes `artifacts=[{"file": "file_id"}]`.
- Removes the `type` attribute from the `AgentToolMetadata` class.
- Adds two …
> Backend: misc fixes

- src/interfaces/coral_web/src/cohere-client/generated/index.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/GenerateTitle.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/UpdateAgent.ts
- src/interfaces/coral_web/src/cohere-client/generated/services/DefaultService.ts
- src/interfaces/coral_web/src/components/Agents/AgentForm.tsx
- src/interfaces/coral_web/src/components/Agents/CreateAgentForm.tsx
- src/interfaces/coral_web/src/components/Agents/UpdateAgentPanel.tsx
- src/interfaces/coral_web/src/hooks/agents.ts
This pull request introduces a new feature to generate a title for a conversation and update the conversation with the generated title. 
- Added a new `GenerateTitle` type, which consists of a `title` field of type `string`.
- Modified the `DefaultService` class to include a new method, …
> chore: generate client types

- src/backend/routers/agent.py
- src/backend/schemas/agent.py
- src/backend/tests/routers/test_agent.py
Fix reported bugs:
- Error when sending empty metadata -> now all elements are deleted
- Other fields not updated when there was metadata -> now everything is updated correctly
- Error when there was no ID -> now a new instance is added when there's no ID
The PR introduces changes to the agent management functionality, specifically enhancing the creation and updating of agents and their associated tool metadata.
- The `update_agent` function in `src/backend/routers/agent.py` has been modified to handle tool metadata updates more efficiently.
- New test cases have been added in `src/backend/tests/routers/test_agent.py` to validate the updated agent creation and updating behavior, including scenarios with new and existing tool metadata.
- The `UpdateAgentToolMetadata` …
> Agent: fix update metadata

- src/interfaces/coral_web/src/cohere-client/generated/index.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/GenerateTitle.ts
- src/interfaces/coral_web/src/cohere-client/generated/models/UpdateAgent.ts
- src/interfaces/coral_web/src/cohere-client/generated/services/DefaultService.ts
- src/interfaces/coral_web/src/components/Agents/AgentForm.tsx
- src/interfaces/coral_web/src/components/Agents/AgentToolFielPicker.tsx
- src/interfaces/coral_web/src/components/Agents/AgentToolFilePicker.tsx
- src/interfaces/coral_web/src/components/Agents/CreateAgent.tsx
- src/interfaces/coral_web/src/components/Agents/UpdateAgent.tsx
This PR refactors the way `<CreateAgent />` and `<UpdateAgent />` use `<AgentForm />` by improving type-safety using generics for `fields` and `setFields` instead of using a `onChange` handler.
Additionally prepares for updating the agents tools artifacts https://github.com/cohere-ai/cohere-toolkit/pull/340
This PR introduces the `GenerateTitle` type and the corresponding `generateTitleV1ConversationsConversationIdGenerateTitlePost` method in the `DefaultService` class. It also updates the `UpdateAgent` type and related components.
- Adds the `GenerateTitle` type, which consists of a `title` field of type `string`.
- Implements the `generateTitleV1ConversationsConversationIdGenerateTitlePost` method in the `DefaultService` class. This method generates a title for a …
> fix(toolkit): refactor agent components to improve data flow and type-safety

- src/interfaces/coral_web/src/env.mjs
Though we are setting environment variable values for `FRONTEND_HOSTNAME` during the setup flow, for ease of use it's nice to have a default value for this in the frontend so that it doesn't fail to launch entirely if the value is missing.
This pull request updates the `env.mjs` file in the `src/interfaces/coral_web/src` directory. Specifically, it modifies the `client` object within the `createEnv` function:
- The `NEXT_PUBLIC_FRONTEND_HOSTNAME` field now has an optional default value of `'http://localhost:4000''.
> frontend: Use localhost:4000 as a default FRONTEND_HOSTNAME value

- src/interfaces/coral_web/src/hooks/conversation.tsx
We aren't properly filtering conversations for the default agent, which has an id of `null`. We should also add the `agentId` to the query key for better caching.
https://github.com/cohere-ai/cohere-toolkit/assets/5898755/eb48fcce-8f3d-4f25-a061-81f2bfba847c
The pull request makes changes to the `useConversations` hook in the `conversation.tsx` file. 
The changes in this PR update the `queryKey and `queryFn` options used by the `useQuery` hook in the `useConversations` hook. The `queryKey` now includes the `params.agentId`, and the `queryFn` has been modified to filter conversations based on the provided `agentId`.
- The `queryKey` now includes `['conversations', params.agentId]` instead of just `['conversations'].
- The `queryFn` now uses the …
> coral-web: filter conversations for default assistant

- src/backend/services/metrics.py
The pull request makes changes to the `metrics.py` file in the backend services of a Python application. The modifications aim to improve error handling, logging, and asynchronous operations related to metrics collection and reporting.
Here's a summary of the changes:
- Added imports for `get_header_user_id` and `logging` modules.
- Introduced a logger …
> Metrics: fix error when data is None and improve logger

- src/interfaces/coral_web/src/components/Conversation/MessagingContainer.tsx
- src/interfaces/coral_web/src/components/Conversation/index.tsx
- src/interfaces/coral_web/src/components/MessageRow.tsx
- src/interfaces/coral_web/src/components/ToolEvents.tsx
- src/interfaces/coral_web/src/hooks/chat.ts
https://github.com/cohere-ai/cohere-toolkit/assets/140425731/b48210b3-c52a-4fc5-9c08-36d52ce5a09d
This pull request introduces the `isStreamingToolEvents` state and prop to various components and hooks in the `coral_web` interface. This new feature allows the rendering of a "Working on it" message with an ellipsis animation while tool events are being …
> coral-web: show loading text when tool events are still streaming in

- src/interfaces/coral_web/Dockerfile
The `.nvmrc` was recently updated to require Node 20.12.2, so we need to upgrade the base image in the Dockerfile as well
> tools: Make sure the Coral Dockerfile is using Node 20 as well

- src/interfaces/coral_web/src/components/Conversation/Composer/index.tsx
- src/interfaces/coral_web/src/hooks/chat.ts
Allows user to hit the stop/square button in the composer mid generation to abort the process
https://github.com/cohere-ai/cohere-toolkit/assets/140425731/070fc3cc-5600-438c-9d22-79f286c7ad8e
This pull request makes changes to the `src/interfaces/coral_web/src` directory, specifically within the `Composer` component and the `useChat` hook. 
The changes in this PR focus on updating error handling and …
> coral-web: enable message generation cancelling

- src/interfaces/coral_web/src/components/Citations/Citation.tsx
https://github.com/cohere-ai/cohere-toolkit/assets/19353218/0e4c0e33-ea27-4cee-8cf5-56fcb139bd37
This pull request makes changes to the `Citation.tsx` component in the `src/interfaces/coral_web/src/components/Citations` directory. 
The `Citation` component renders a list of citations with associated documents. The changes in this PR modify the logic for displaying citations and documents based on selection state and visibility settings. 
- Updated the condition to return `null` when there are no relevant documents or when a citation is not selected.
- Introduced a new variable, `uniqueDocumentsUrls`, to store unique document URLs.
- Modified the condition for rendering the number of references and the associated icon button. Now, it considers the length of …
> feat(toolkit): Dedupe links when URL is cited multiple times in the references

- src/backend/services/metrics.py
The pull request introduces changes to the `src/backend/services/metrics.py` file, specifically to the `report_metrics` function. 
The updates involve adding a check for the `METRICS_LOGS_CURLS` environment variable before logging the signal curl. 
Here's a summary of the changes: 
- The `METRICS_LOGS_CURLS` environment variable is introduced and set to …
> metrics: allow suppressing curl logs

- src/interfaces/coral_web/src/cohere-client/client.ts
- src/interfaces/coral_web/src/components/Conversation/Composer/index.tsx
This pull request introduces changes to two files: `client.ts` and `index.tsx`. Here's a summary:
- The `openWhenHidden` option in the `CohereClient` class constructor in `client.ts` is now set to `true`. This ensures that requests continue even when the tab is hidden and resume/retry when it becomes visible again.
- In `index.tsx`, the `useSlugRoutes` hook is imported, and the `agentId` variable is now used to conditionally render the `FirstTurnSuggestions` component.
- **client.ts**: The `openWhenHidden` option is added to the `CohereClient` class constructor options, ensuring that requests are not paused when the tab is hidden.
- **index.tsx**:
- The `useSlugRoutes` hook is imported, and the `agentId` variable is now used.
- The `FirstTurnSuggestions` component is …
> fix(toolkit): Requests will go into pending on window visibility hidden

- docker-compose.yml
- src/backend/cli/main.py
- src/interfaces/coral_web/Dockerfile
This pull request makes changes to the `docker-compose.yml` file and adds a new build target feature to the backend.
- Adds quotes around the port values.
- Moves the `volumes` property under the `db` service to be consistent with other services.
- Updates the `build` property of the `frontend` service to include a `target` property, which is set to `${BUILD_TARGET:-prod}`.
- Adds a new `BuildTarget` class with `DEV` and `PROD` as possible values.
- Introduces a `build_target_prompt` function to prompt the user to select a build target.
- Integrates the build target selection into the `start` function, setting the `BUILD_TARGET` secret.
- Adds a `dev` stage to the Dockerfile, using `yarn dev` or `npm run dev` based on the presence of `yarn.lock` or `package-lock.json`. …
> infra(toolkit): fix deployment target for UI on prod and dev

- src/interfaces/coral_web/src/components/Conversation/Composer/EnabledDataSources.tsx
This pull request makes changes to two files: `custom.py` and `EnabledDataSources.tsx`. 
- The `custom.py` file has been updated to include a new parameter, `user_id`, in the `send_log_message` function call. 
- In the `EnabledDataSources.tsx` file, the `useSlugRoutes` hook has been imported, and the `agentId` variable is now used to conditionally disable the removal of tools for assistants. 
- Additionally, the `onDelete` prop in the `DataSourceChip` component has been made optional, and the code for rendering the close button has been updated to include a check for the `onDelete` prop before rendering it.
- Added `user_id` as a parameter in the `send_log_message` function call.
- Imported the `useSlugRoutes` hook and destructured the `agentId` variable.
- Added a …
> fix(toolkit): do not allow to remove tools on composer for assistants

- src/interfaces/coral_web/src/hooks/chat.ts
Before this fix, when we received a `search-results` event, we didn't increase the `currentToolEventIndex`. The same event was used when we received a new `tool-call-chunk`. This one didn't have the `tool_calls` property initialized, and it failed to add the first "chunk" of the stream, which was the name, so the whole stream event was lost. 
Also, I ignored the `search results` from a `python_interpreter` because they are not really formatted or prepared to be shown, and they are not required.
Closes OS-2284
> fix: increase toolEvents when pushing search results event

- Makefile
This PR changes the `make dev` command so that it both watches the files with `docker compose watch`, and runs `docker compose up` explicitly so that the logs show up in the console.
The `docker compose watch` command previously being used starts the services up, but it suppresses log output. That is by design and there is no flag to make it show the log output from the services. To get around this, the change in this PR takes the approach of running both commands in separate processes. The flag `--no-up` is added to `docker compose watch`, which changes its behavour to only watch, and not start the services up automatically.
The `Makefile` has been updated to include new targets and modify the existing `dev` target.
- The `dev` target now invokes the …
> backend: Show logs when running make dev command

- src/interfaces/coral_web/src/components/Conversation/Composer/ComposerFiles.tsx
- src/interfaces/coral_web/src/components/Conversation/Composer/ComposerToolbar.tsx
- src/interfaces/coral_web/src/hooks/files.ts
- src/interfaces/coral_web/src/pages/[[...slug]].tsx
- src/interfaces/coral_web/src/utils/format.ts
Fixes bugs with the file upload component:
- Remove errors on new files uploaded
- Limit file size to 20mb
- When user removes a file, it is also removed from the composer tools
- Accept file types is not working as expected
This pull request makes changes to the file uploading functionality. 
- Adds a new utility function, `fileSizeToBytes`, to convert file size from megabytes to bytes.
- Updates the `useFileActions` hook to:
- Clean up uploading files with errors.
- Validate the file size against a new constant, `MAX_FILE_SIZE`, before uploading.
- Updates the `ComposerFiles` component to:
- Handle file deletion using a new `handleComposerFileDelete` function.
- Use the `fileIds` param from the `useParamsStore` store.
- Updates the `ComposerToolbar` component to …
> fix(toolkit): Improves file upload component and user experience

- src/interfaces/coral_web/src/components/Conversation/Composer/ComposerError.tsx
- src/interfaces/coral_web/src/components/Conversation/Composer/index.tsx
- src/interfaces/coral_web/src/components/Layout.tsx
- src/interfaces/coral_web/src/components/Settings/AgentsToolsTab.tsx
- src/interfaces/coral_web/src/components/Settings/SettingsDrawer.tsx
- src/interfaces/coral_web/src/components/Settings/SettingsTab.tsx
- src/interfaces/coral_web/src/pages/[[...slug]].tsx
- src/interfaces/coral_web/src/pages/discover.tsx
- src/interfaces/coral_web/src/pages/new.tsx
Hides agents related UI additions behind the `USE_AGENTS_VIEW` environment variable
https://github.com/user-attachments/assets/6945d6b3-d7a3-47eb-88c2-642171c3f038
https://github.com/user-attachments/assets/b2122b40-b132-43a2-ae1f-621b85eaf5b8
This PR introduces a new `AgentsLayout` component and makes changes to the `Layout` component. It also adds a new `SettingsTab` component and modifies the `ToolsTab` component.
- The `Layout` component now includes additional imports, props, and state/context usage. It renders the `NavigationBar`, `Banner`, and `SettingsDrawer` components, and manages the layout for different device sizes.
- The new `AgentsLayout` component is introduced, which seems to be a variation of the `Layout` component with some differences in the rendered …
> coral-web: hide agents views components behind env variable

- src/interfaces/coral_web/src/env.mjs
- src/interfaces/coral_web/src/hooks/tools.ts
This pull request makes Google Drive integration optional in the `coral_web` interface. 
Previously, the `NEXT_PUBLIC_GOOGLE_DRIVE_CLIENT_ID` and `NEXT_PUBLIC_GOOGLE_DRIVE_DEVELOPER_KEY` environment variables were required for the Google Drive picker to function. Now, these variables are optional, and the picker will display an informational message if Google Drive is unavailable due to missing credentials.
- In `env.mjs`, the `NEXT_PUBLIC_GOOGLE_DRIVE_CLIENT_ID` and `NEXT_PUBLIC_GOOGLE_DRIVE_DEVELOPER_KEY` variables are now marked as `optional`.
- In `tools.ts`, added a check to display an informational message if `NEXT_PUBLIC_GOOGLE_DRIVE_CLIENT_ID` or `NEXT_PUBLIC_GOOGLE_DRIVE_DEVELOPER_KEY` are missing.
- Updated the `clientId` and `developerKey` …
> fix(toolkit): make google drive env vars optional

- src/interfaces/coral_web/src/cohere-client/client.ts
- src/interfaces/coral_web/src/pages/_app.tsx
- src/interfaces/coral_web/src/pages/login.tsx
Restore the link to the Register page if the backend has been configured for login with a username and password.
Also fixes an issue introduced with the change to the new API client that broke Authorization headers.
This pull request makes changes to the `src/interfaces/coral_web/src/cohere-client/client.ts` and `src/interfaces/coral_web/src/pages/login.tsx` files.
The changes in this PR mainly involve updating the `HEADERS` property in the `CohereClient` class and modifying the `LoginPage` component in the `login.tsx` file.
- Modified the `HEADERS` property in the `CohereClient` class to be an async function that returns the headers.
- Added the `AuthLink` component import from `'@/components/AuthLink''.
- Introduced `welcomePageProps` to hold the `title` and …
> frontend: Add back the Register link if basic auth is enabled

- docs/auth_guide.md
The pull request describes updates to the authentication (auth) strategies implementation guide. It includes changes to the existing content and introduces new sections.
- The `AUTH_SECRET_KEY` variable-related instructions have been rephrased for clarity.
- A new section on **Enabling Proof of Key Code Exchange (PKCE)** has been added, detailing:
- The …
> Add PKCE docs

- src/interfaces/coral_web/src/hooks/chat.ts
- src/interfaces/coral_web/src/stores/index.ts
- src/interfaces/coral_web/src/stores/slices/filesSlice.ts
This pull request introduces a new `clearUploadingErrors` function to the `filesSlice` and updates the `useFilesStore` and `useChat` hooks to use this new function.
- `clearUploadingErrors` is added to the `useFilesStore` hook in `index.ts`.
- `clearUploadingErrors` is called in the `useChat` hook in `chat.ts`.
- `clearUploadingErrors` is defined in `filesSlice.ts` to filter out uploading files with errors.
> fix(toolkit): clear file errors on message send

- src/interfaces/coral_web/src/components/Conversation/index.tsx
- src/interfaces/coral_web/src/hooks/files.ts
This pull request updates the `handleUploadFile` function in the `Conversation` component and the `useFileActions` hook to remove the explicit dependency on the `conversationId` parameter. 
- The `handleUploadFile` function in `index.tsx` no longer includes the `conversationId` parameter when calling the `uploadFile` function. 
- The `useFileActions` hook in `files.ts` now destructures `conversation` from `useConversationStore`. 
- The `handleUploadFile` function in `files.ts` no longer includes the `conversationId` parameter. 
- When calling the `uploadFile` function in `files.ts`, the `conversationId` property is now passed by destructuring `conversation.id` from the `conversation` object. 
- When checking for the existence of a `conversationId`, the code now checks …
> fix(toolkit): Generating new convo_id for upload files on brand new conversation

- src/backend/config/routers.py
- src/backend/services/auth/jwt.py
- src/backend/tests/routers/auth/test_authorization_header.py
This pull request makes changes to the backend code, specifically modifying the JWT token expiry time and updating code comments.
The `JWTService` class in `jwt.py` has been updated to change the expiry time of JWT tokens from 3 months to 90 days. This is achieved by modifying the `EXPIRY_DAYS` attribute and the `exp` key in the JWT payload. …
> Auth: fix expiry date

- src/backend/model_deployments/cohere_platform.py
- src/backend/schemas/metrics.py
- src/backend/services/metrics.py
The pull request updates the `timestamp` field in the `MetricsDataBase` class and the `get_event_data` function to use the current Unix timestamp in seconds. 
- The `timestamp` field in the `MetricsDataBase` class now has a default value of the current Unix timestamp in seconds.
- The `get_event_data` function now includes a `now_unix_seconds` variable, which stores the current Unix timestamp in seconds and is used as the `timestamp` value in the `MetricsData` object.
> metrics: send the correct time from event

- src/backend/schemas/snapshot.py
- src/backend/services/snapshot.py
Users were getting a 500 when sharing an agent conversation, this PR fixes that. It also removes agent information from the shared conversation response.
> Snapshot: fix share agent convo + remove agent data from response

- src/interfaces/coral_web/src/components/Agents/CreateAgent.tsx
- src/interfaces/coral_web/src/components/Agents/UpdateAgent.tsx
This pull request updates the `CreateAgent` and `UpdateAgent` components in the `src/interfaces/coral_web/src/components/Agents` directory. 
**Summary**
- The PR introduces changes to the way artifacts are handled when the tool name is `TOOL_GOOGLE_DRIVE_ID`. 
- It ensures that duplicate artifacts are removed by using the `uniqBy` function from Lodash. 
- The `tools_metadata` array is updated to include only unique artifacts for `TOOL_GOOGLE_DRIVE_ID`, while keeping other tool artifacts unchanged. 
**Code Changes**
- The `uniqBy` function from Lodash is imported in both `CreateAgent.tsx` and `UpdateAgent.tsx`.
- In `CreateAgent.tsx`, when handling data from Google Drive, the code now constructs an `updatedArtifacts` array, which includes existing artifacts for …
> feat(toolkit): do not override google drive files on new selection

- src/interfaces/coral_web/src/components/ReadOnlyConversation.tsx
| Before | After |
|--------|-------|
| ![Screenshot 2024-07-18 at 17 58 53](https://github.com/user-attachments/assets/f6983b47-4f04-4287-82e6-04126394d86a) | ![Screenshot 2024-07-18 at 18 00 57](https://github.com/user-attachments/assets/51e8859f-f692-4216-9a2b-b032947f8193) |
This pull request updates the `ReadOnlyConversation` component in the `src/interfaces/coral_web/src/components/ReadOnlyConversation.tsx` file. Specifically, the changes are:
- The `justify-between` class has been added to the `div` element within the `messages.map` loop. This class applies a flex justification rule, likely aligning items to the start and end of the flex container.
> coral-web: fix citation alignment in read only convo

- src/backend/config/routers.py
- src/backend/routers/chat.py
This pull request updates the `validate_authorization` dependency in the `src/backend/config/routers.py` file and removes a `print` statement from the `chat_stream` function in `src/backend/routers/chat.py`.
- `src/backend/config/routers.py`:
- The `validate_authorization` dependency is uncommented and added to the "auth" list for the `RouterName` …
> Agents: validate auth

- charts/cohere-toolkit/templates/backend.yaml
- charts/cohere-toolkit/templates/frontend.yaml
- charts/cohere-toolkit/templates/terrarium.yaml
- charts/cohere-toolkit/values.yaml
Closes EINF-1016
This pull request adds `livenessProbe` and `readinessProbe` to the `backend.yaml`, `frontend.yaml`, and `terrarium.yaml` files.
- The `livenessProbe` is configured to perform an HTTP GET request to the `/health` endpoint for `backend.yaml` and to the root endpoint (`/`) for `frontend.yaml` and `terrarium.yaml`.
- The `readinessProbe` is set up similarly, making an HTTP GET request to the respective endpoints.
- Both probes use the `http` port.
> feat(helm): liveness and readiness probes

- src/interfaces/assistants_web/src/components/Agents/AgentsSidePanel.tsx
- src/interfaces/assistants_web/src/components/Conversation/Header.tsx
- src/interfaces/assistants_web/src/hooks/chatRoutes.ts
- src/interfaces/assistants_web/src/hooks/conversation.tsx
- src/interfaces/coral_web/src/components/Agents/AgentsSidePanel.tsx
- src/interfaces/coral_web/src/components/Conversation/Header.tsx
- src/interfaces/coral_web/src/hooks/chatRoutes.ts
- src/interfaces/coral_web/src/hooks/conversation.tsx
This PR introduces a new `useNavigateToNewChat` hook and updates the AgentsSidePanel and Header components to use this hook for handling new chat functionality.
- The `useNavigateToNewChat` hook is defined in `chatRoutes.ts`. It utilizes the useRouter, useAgentsStore, useConversationStore, useCitationsStore, and useParamsStore hooks to handle navigation to a new chat.
- In `AgentsSidePanel.tsx`, the useRouter, useAgentsStore, useCitationsStore, useConversationStore, and useParamsStore hooks are replaced with useNavigateToNewChat. The handleNewChat function is removed, and the button's onClick event now calls the navigateToNewChat function.
- In `Header.tsx`, the useRouter, useAgentsStore, useCitationsStore, useConversationStore, and useParamsStore hooks are replaced …
> fix(toolkit): centralize chat navigation

- src/backend/services/chat.py
The pull request updates the `response_id` assignment in the `generate_chat_response` and `generate_chat_stream` functions within `src/backend/services/chat.py`.
The changes in this pull request modify how the `response_id` is assigned in the `generate_chat_response` and `generate_chat_stream` functions. Instead of setting `response_id` to …
> [2/N] Logs: replace response ID by trace ID

- src/interfaces/assistants_web/src/hooks/chat.ts
- src/interfaces/coral_web/src/hooks/chat.ts
It looks like, with the new app router, the clean-up function on `chat.ts`, which removes the `streamingMessage` state, isn't executed after the first iteration.
I removed the condition to check if we had a `streamingMessage` before adding it to the conversation and instead pushed the fulfilled message directly to the conversation.
Closes TLK-885
> frontend(web): fix attaching previous streaming message to the new chat

- src/backend/config/settings.py
- src/backend/services/logger/strategies/structured_log.py
- src/backend/services/logger/utils.py
Add default values for all settings, to fix validation when there is no config 
This PR updates the default values for various settings in the `settings.py` file. It also removes some unnecessary imports in the `structured_log.py` and `utils.py` files.
- Updates the default values for multiple fields in the `GoogleOAuthSettings`, `OIDCSettings`, `AuthSettings`, `ToolSettings`, `DatabaseSettings`, `RedisSettings`, `SageMakerSettings`, `AzureSettings`, `CoherePlatformSettings`, `SingleContainerSettings`, `BedrockSettings`, `DeploymentSettings`, and `LoggerSettings` classes.
- Sets `enabled_auth` and `enabled_tools` to `None` in the `AuthSettings` and `ToolSettings` classes, respectively.
- Removes the `sys` import.
- Removes the `logging` import.
> Add default settings - when there is no config 

- src/interfaces/assistants_web/package-lock.json
- src/interfaces/assistants_web/package.json
- src/interfaces/assistants_web/src/app/(main)/layout.tsx
- src/interfaces/coral_web/package-lock.json
- src/interfaces/coral_web/package.json
- src/interfaces/coral_web/src/app/(main)/layout.tsx
When no auth strategies are enabled, skip checking auth.
The changes include:
- Adding the `cross-fetch` package and its dependencies to `package.json` and `package-lock.json`.
- Importing the `cross-fetch` package and related modules in `layout.tsx`.
- Modifying the `layout.tsx` file to use the `CohereClient` and `Fetch` functions from the `@/cohere-client` module.
- Introducing a new `makeCohereClient` function to create a `CohereClient` instance with the API hostname and `apiFetch` function.
- Updating the `Layout` component to use the `cohereClient` instance and check for auth strategies before redirecting to the login page.
- **package-lock.json**:
- Added `cross-fetch` and its dependencies (`node-fetch` and `node-fetch`'s dependency `whatwg-url') to the `dependencies` list.
- …
> fix(toolkit): auth when no strategies are enabled

- src/interfaces/assistants_web/.storybook/preview.tsx
Display dark and light mode components in storybook
This pull request updates the rendering of stories in the Storybook for the `assistants_web` interface.
**Changes:**
- Removes the `globalTypes` field from the `preview` object, which includes the `theme` configuration.
- Updates the `decorators` array by modifying the rendering of stories:
- Removes the `context` parameter from the decorator …
> feat(toolkit): display dark and light mode

- docker-compose.yml
- src/interfaces/assistants_web/.env.development
- src/interfaces/assistants_web/.env.production
- src/interfaces/assistants_web/src/app/(main)/layout.tsx
- src/interfaces/assistants_web/src/env.mjs
- src/interfaces/coral_web/.env.development
- src/interfaces/coral_web/.env.production
- src/interfaces/coral_web/src/app/(main)/layout.tsx
- src/interfaces/coral_web/src/env.mjs
React Server Components runs in the server, for our case this means that it runs in the same network that our backend is running, therefore to communicate with the backend we need to specify the internal docker network route to the backend (http://backend/). For the client bundle we still use the exposed port 8000 because requests are performed from an external network from that of docker.
- API_HOSTNAME -> to be used in RSC context
- NEXT_PUBLIC_API_HOSTNAME -> for the client bundle
> fix(toolkit): API host name for RSC

- src/interfaces/assistants_web/src/components/Agents/AgentRightPanel.tsx
- src/interfaces/assistants_web/src/components/Agents/AgentSettings/AgentSettingsForm.tsx
- src/interfaces/assistants_web/src/components/Agents/AgentSettings/DefineStep.tsx
- src/interfaces/assistants_web/src/components/Agents/CreateAgent.tsx
- src/interfaces/assistants_web/src/components/Agents/UpdateAgent.tsx
- src/interfaces/assistants_web/src/components/CollapsibleSection.tsx
- src/interfaces/assistants_web/src/hooks/chat.ts
- src/interfaces/assistants_web/src/stores/index.ts
- src/interfaces/assistants_web/src/stores/slices/agentsSlice.ts
https://github.com/user-attachments/assets/cf4f1339-8815-416e-a872-d05babff6f9e
- Scroll overflow for create/update assistant
- Do not show error message when name is not typed for assistant
- Do not override files on file picker select
- Auto scroll to assistant step on "Next" or "Back"
This pull request makes changes to the assistant settings and UI components. 
The changes include:
- Adding the ability to disable assistant knowledge for specific agents.
- Updating the agent settings form to include data sources by default when creating a new agent.
- Enhancing the collapsible section component to smoothly scroll to the expanded content.
- Refactoring the assistant settings form to include a new "Update" button and rearranging the "Delete Assistant" button.
- …
> fix(dark-mode): fix bugs and improvements to UX

- src/interfaces/assistants_web/src/components/Conversation/Composer/ComposerError.tsx
- src/interfaces/assistants_web/src/components/IconButton.tsx
- src/interfaces/assistants_web/src/components/MessageRow.tsx
- src/interfaces/assistants_web/src/components/ShareModal.tsx
- src/interfaces/assistants_web/src/components/Shared/Button/Button.stories.tsx
- src/interfaces/assistants_web/src/components/Shared/Button/Button.tsx
- src/interfaces/assistants_web/src/components/Shared/CodeSnippet/CodeSnippet.tsx
- src/interfaces/assistants_web/src/components/Shared/CopyToClipboardButton/CopyToClipboardButton.tsx
https://github.com/user-attachments/assets/e9157ff3-6792-4725-8df0-9ea9a2182750
This pull request updates several components by removing the `animate` prop and adding a new logic for the `animate` behavior.
- The `animate` prop is removed from the `Props interface in IconButton.tsx, ComposerError.tsx, MessageRow.tsx, ShareModal.tsx, Button.stories.tsx, CodeSnippet.tsx, and CopyToClipboardButton.tsx.
- In Button.tsx, the `animate` prop is replaced with a new logic that sets `animate` to `true` only when there is an icon and a label or children.
- The `animate` variable in the cellInner function in Button.tsx is moved from the third to the fifth position in the function parameters.
- The animateStyles variable in Button.tsx is removed, and the `animate` class is now …
> feat(toolkit): fix buttons animations

- src/backend/crud/agent.py
- src/backend/database_models/seeders/deplyments_models_seed.py
- src/backend/services/chat.py
- src/backend/tests/routers/test_agent.py
- src/backend/tests/routers/test_chat.py
- Restore chat flow
This PR makes changes to the backend of the application, including database models, chat processing, and testing. 
- Updates the `src/backend/database_models/seeders/deplyments_models_seed.py` file to use SQL commands for inserting data into the `deployments` and `models` tables, replacing the previous method of using the `Session` object. 
- Removes some code related to `default_user` and `default_organization` in the `deployments_models_seed` function. 
- Removes the `default_agent` code block and associated code from the same function. 
- Introduces the `uuid4` function from the `uuid` module to generate unique IDs for the `deployment_id` and `model_id`. 
- Updates the `src/backend/services/chat.py` file by removing some code related to deployment …
> Restore chat flow

- src/interfaces/assistants_web/src/app/(main)/layout.tsx
- src/interfaces/assistants_web/src/components/Agents/DiscoverAgentCard.tsx
- src/interfaces/assistants_web/src/components/Agents/DiscoverAgents.tsx
- src/interfaces/assistants_web/src/components/Agents/LeftPanel.tsx
- src/interfaces/assistants_web/src/components/ConversationList/ConversationList.tsx
- src/interfaces/assistants_web/src/components/Shared/Button/Button.tsx
- src/interfaces/assistants_web/src/components/Shared/CopyToClipboardButton/CopyToClipboardButton.tsx
- fix: button `stretch` prop when is used as `secondary` vs `primary` kind
- fix: fill color Copy to clipboard button
- fix: button animation with a custom icon
- fix: default text color for the default theme
- fix: add default agent to /discover page
- style: not show any agent group when there is no agents
- refactor: rename `AgentSidePanel` to `LeftPanel`
- refactor: rename `AgentList` to `ListConversation`
- style: hide scrollbar when there is no conversations
- style: animate on hover `DiscoverAgentCard`
> refactor: rename files and bug fixes

- src/backend/services/file.py
The `get_files_by_agent_id` function in `src/backend/services/file.py` has been updated to include a default value for the generator being empty. This is achieved by adding an empty list `[]`.
---
- The function `get_files_by_agent_id` has been modified:
- An empty tuple `(`, `),` is added to the line containing `tool_metadata.artifacts`.
- An empty …
> File Service: fix empty generator

- src/interfaces/assistants_web/src/app/(main)/(chat)/Chat.tsx
- src/interfaces/assistants_web/src/cohere-client/client.ts
- src/interfaces/assistants_web/src/cohere-client/generated/schemas.gen.ts
- src/interfaces/assistants_web/src/cohere-client/generated/services.gen.ts
- src/interfaces/assistants_web/src/cohere-client/generated/types.gen.ts
- src/interfaces/assistants_web/src/components/Agents/AgentSettings/AgentSettingsForm.tsx
- src/interfaces/assistants_web/src/components/Agents/DiscoverAgents.tsx
- src/interfaces/assistants_web/src/components/Agents/UpdateAgent.tsx
- src/interfaces/assistants_web/src/components/Conversation/Composer/DragDropFileUploadOverlay.tsx
- src/interfaces/assistants_web/src/components/ConversationList/ConversationCard.tsx
- src/interfaces/assistants_web/src/components/EditEnvVariablesButton.tsx
- src/interfaces/assistants_web/src/hooks/agents.ts
- src/interfaces/assistants_web/src/hooks/conversation.tsx
- src/interfaces/assistants_web/src/hooks/files.ts
- src/interfaces/assistants_web/src/hooks/generateTitle.ts
- src/interfaces/assistants_web/src/hooks/snapshots.ts
- src/interfaces/assistants_web/src/hooks/streamChat.ts
- src/interfaces/assistants_web/src/stores/slices/citationsSlice.ts
- src/interfaces/assistants_web/src/stores/slices/filesSlice.ts
- src/interfaces/assistants_web/src/types/message.ts
Updates the OpenAPI schema
This pull request makes changes to the agent and conversation data models and their respective components. It also adds new features and fixes to the Cohere client.
- **Agent data model changes**:
- Added deployments and model as optional fields.
- Changed deployment and tools_metadata to optional fields.
- Added created_at and updated_at fields to AgentToolMetadata.
- **Conversation data model changes**:
- Removed user_id and organization_id fields.
- **Cohere client changes**:
- Added CreateDeployment, UpdateDeployment, and DeleteDeployment methods.
- Added CreateOrganization, UpdateOrganization, and DeleteOrganization methods.
- Added CreateModel, UpdateModel, and DeleteModel methods.
- Added ListModels and ListOrganizations methods.
- …
> fix(toolkit): update OpenAPI schema

- charts/cohere-toolkit/Chart.lock
- charts/cohere-toolkit/Chart.yaml
- charts/cohere-toolkit/templates/_helpers.tpl
- charts/cohere-toolkit/templates/backend.yaml
- charts/cohere-toolkit/values.yaml
This PR adds a Redis helm chart dependency and sets the `REDIS_URL` and network access for `toolkit-backend`.
This pull request adds a Redis dependency to the Cohere Toolkit. 
- The `dependencies` section in `Chart.lock` and `Chart.yaml` now includes a Redis entry with the repository, version, digest, and generation time.
- The `cohere-toolkit.redis-url` template in `_helpers.tpl` is defined to format the Redis connection string.
- The `backend.yaml` now includes a reference to the Redis host in the `spec` section and adds the `REDIS_URL` to the `stringData` section, using the `cohere-toolkit.redis-url` template.
- The `values.yaml` file has been updated to include Redis-related configurations, such as enabling Redis, setting a full name override, enabling …
> infra: Added Redis

- .github/scripts/check_revision_ids.py
The migrations files have a date before the revision id now, so splitting the filenames is breaking the check.
The `main` function in `check_revision_ids.py` has been modified to check for duplicate file names instead of revision IDs.
- The `revision_ids` list is no longer created by extracting the first part of each file name before the underscore.
- The condition to raise an exception has been changed to check if the length of `files` is not equal to the length of a set of `files`, indicating duplicate file names.
- The exception message has been updated to reflect the change in logic, now raising an exception if a "Duplicate file name" is found.
- The print statement remains the same, indicating that "All revision IDs are unique."
> CI: fix check duplicate revision id

- charts/cohere-toolkit/values.yaml
This pull request makes changes to the `charts/cohere-toolkit/values.yaml` file.
- The `livenessProbe` and `readinessProbe` configurations for the `backend`, `frontend`, and `terrarium` sections have been commented out.
- The `path` and `port` settings for the `httpGet` requests within these probes have been removed.
The impact of these changes is to …
> chore(helm): do not set probes by default

- src/interfaces/assistants_web/src/components/Agents/AgentRightPanel.tsx
- src/interfaces/assistants_web/src/components/Conversation/Header.tsx
- src/interfaces/assistants_web/src/components/Shared/CodeSnippet/CodeSnippet.tsx
- src/interfaces/assistants_web/src/components/Shared/Markdown/tags/Iframe.tsx
Fixes background color for the Iframe artifact output.
This pull request updates the `CodeSnippet.tsx` and `Iframe.tsx` components to support a dark theme.
- Added `dark:` modifiers to the `className` props in `CodeSnippet.tsx` and `Iframe.tsx` to apply dark theme styles.
- Modified the `className` prop in `Iframe.tsx` to use a darker background color for the `TabList` component.
> fix(toolkit): dark mode for iframe artifact

- src/interfaces/assistants_web/src/hooks/chat.ts
fix: the `composerFile` is nullable, so if it's null it will fall into empty string
> fix: use actual conversation_id or undefined

- .github/workflows/python-lint.yml
Pins the version to 0.6.0 in the python-lint workflow
> infra: pin version of ruff in github workflow

- src/interfaces/assistants_web/src/hooks/tools.ts
- src/interfaces/assistants_web/src/utils/citations.ts
The pull request makes changes to the `replaceTextWithCitations` function in the `citations.ts` file. This function is responsible for replacing text with citations and handling references.
Here are the key changes:
- The function now includes a `filter` step before iterating over the `citations`. It filters out citations that do not have any `document_ids`.
- The rest of the function remains largely the same, with minor formatting changes and the addition of comments to explain the purpose of certain code blocks.
- The logic for handling the case where `citeStart` is higher than the length of the text has been retained, adding the reference to the bottom of the text.
- The `fixedText` variable is still assigned the result of calling `fixMarkdownImagesInText` on …
> fix(toolkit): do not highlight citations with no documents

- src/interfaces/assistants_web/src/components/Agents/AgentSettings/AgentSettingsForm.tsx
- src/interfaces/assistants_web/src/components/Agents/CreateAgent.tsx
- src/interfaces/assistants_web/src/components/Agents/Settings.tsx
- src/interfaces/assistants_web/src/components/Agents/UpdateAgent.tsx
- src/interfaces/assistants_web/src/hooks/tools.ts
- src/interfaces/assistants_web/src/utils/getToolAuthUrl.ts
Closes OS-2422
Integrates redirect URL for tool auth.
We currently have 3 different pages from where users can authenticate their GDrive. 
- `/settings`
- `/new`
- `/edit/:agent_id`
For the tool auth redirection we had to introduce deep linking state management, for which we use the `state` query param in the tool auth, where we pass a value of `frontend_redirect` which contains the URL the flow will redirect once it successfully gets the auth token. 
For the case when the user has state that we want to preserve, we can pass a hash of the JSON object for the state we want, in this case we use `atob` and `btoa` to encode and decode the state, which we will persist once the page loads with the value in the query params.
> fix(toolkit): integrate redirect URL for tool auth

- src/interfaces/assistants_web/src/components/Conversation/Composer/DataSourceMenu.tsx
- src/interfaces/assistants_web/src/constants.ts
- Default and hide web scrape tool
- Show correct count of tools in composer toolbar
This pull request updates the `DataSourceMenu` component in the `Conversation/Composer` section of the assistants web interface. 
- Introduces a new constant `isBaseAgent` to store the result of the `checkIsBaseAgent(agent)` function.
- Updates the …
> fix(toolkit): feedback nits

- src/backend/routers/agent.py
- src/backend/schemas/file.py
- src/backend/services/file.py
- src/backend/tools/files.py
This pull request makes changes to the file handling and indexing mechanisms in the backend services. 
**Changed Files:**
- `src/backend/routers/agent.py`
- `src/backend/schemas/file.py`
- `src/backend/services/file.py`
- `src/backend/tools/files.py`
**Summary:**
- The `File` class in `src/backend/schemas/file.py` has been updated to make the …
> backend: more compass file fixes

- src/interfaces/assistants_web/src/components/AgentSettingsForm/DefineStep.tsx
- src/interfaces/assistants_web/src/components/AgentSettingsForm/index.tsx
- src/interfaces/assistants_web/src/components/UI/Tooltip.tsx
https://github.com/user-attachments/assets/efafa9ed-0ebe-48cf-a91d-67f280a4cb23
This pull request makes changes to the `AgentSettingsForm` component and its `DefineStep` sub-component.
The `AgentSettingsForm` component now includes an additional prop, `isNewAssistant`, which is passed to the `DefineAssistantStep` sub-component. This prop is used to conditionally render either a `Textarea` for custom …
> feat(toolkit): hide instruction textarea for new assistants

- Makefile
- src/community/tests/tools/test_arxiv.py
- src/community/tests/tools/test_clinicaltrials.py
- src/community/tests/tools/test_llama_index.py
- src/community/tests/tools/test_pub_med.py
- src/community/tools/arxiv.py
- src/community/tools/clinicaltrials.py
- src/community/tools/connector.py
- src/community/tools/llama_index.py
- src/community/tools/pub_med.py
- src/community/tools/wolfram.py
Fixes failing community tests.
This PR introduces changes to the community tools and tests. 
The main updates include:
- Refactoring the `run-community-tests` command in `Makefile` to use `poetry` directly instead of `docker compose`.
- Modifying the test functions in `test_arxiv.py`, `test_clinicaltrials.py`, `test_llama_index.py`, and `test_pub_med.py` to use the `pytest` async marking and async function calls.
- Removing the `ctx` parameter from the `call` functions in `arxiv.py`, `clinicaltrials.py`, `connector.py`, `llama_index.py`, `pub_med.py`, and `wolfram.py`.
The PR also includes some minor code formatting adjustments.
> fix: failing community tests

- src/interfaces/assistants_web/Dockerfile
- src/interfaces/assistants_web/package-lock.json
- src/interfaces/assistants_web/package.json
- src/interfaces/assistants_web/patches/react-scroll-to-bottom+4.2.0.patch
This fixes the React warnings of package `react-scroll-to-bottom` regarding `defaultProps`. Package development seems to be stalled at the moment, therefore applying as patch.
Fix is automatically applied when running node package install.
Reference: [PR on `react-scroll-to-bottom`](https://github.com/compulim/react-scroll-to-bottom/pull/141)
> fix(frontend): remove `defaultProps` from `react-scroll-to-bottom`

- CODEOWNERS
There are several dependency upgrades that can only be merged with a codeowner approval, adding myself to the list so I can review and approve the frontend bumps without having to ping and disturb constantly
> chore: Add more frontend codeowners to deal with security issues

- src/backend/routers/deployment.py
- src/backend/tests/unit/routers/test_deployment.py
- src/community/config/deployments.py
- src/community/model_deployments/hugging_face.py
- Huggingface deployment fixes
This PR introduces changes to the deployment configuration and model handling, primarily focused on the HuggingFaceDeployment class.
The PR modifies the `deployment.py` and `hugging_face.py` files, updating the deployment configuration and enhancing the HuggingFaceDeployment class. It adds new imports, modifies the `__init__` method, and introduces a new `_clean_text` method for text processing. The `invoke_chat_stream` function now includes argument descriptions, and the `_build_chat_history` method has been updated to accept `ChatMessage` objects.
- **deployment.py**:
- The `available_deployments` list is now named `available_db_deployments` and is populated with deployments from `AVAILABLE_MODEL_DEPLOYMENTS`.
- The …
> BE: Huggingface deployment fixes

- src/backend/database_models/seeders/deplyments_models_seed.py
- src/backend/model_deployments/cohere_platform.py
This pull request introduces changes to two files, `src/backend/database_models/seeders/deplyments_models_seed.py` and `src/backend/model_deployments/cohere_platform.py`.
This file undergoes the following modifications:
- Addition of four new dictionaries: `"c4ai-aya-23-35b"`, `"command-r-08-2024"`, `"command-r-plus-08-2024"`, and `"c4ai-aya-23-35b"`. These dictionaries are nested within the `ModelDeploymentName.SingleContainer` and `ModelDeploymentName.MultiContainer` objects.
The `list_models` function is updated to streamline the filtering process by removing unnecessary indentation and simplifying the list comprehension.
> backend: add new Cohere Platform models to seeder

- src/interfaces/slack_bot/package-lock.json
- src/interfaces/slack_bot/package.json
The bolt package had a dependency graph that included a package with a security vulnerability, so I've bumped it to the latest version. At the same time I saw a warning about prism and prism/client versions being out-of-sync, so I've bumped both to the latest versions.
This PR updates the `@prisma/client` dependency to version `^5.20.0` in the `package.json` and `package-lock.json` files.
- The `@prisma/client` dependency is updated to version `^5.20.0` in the `package.json` file.
- The `@prisma/client` dependency is updated to version `^5.20.0` in the `package-lock.json` file.
> slackbot: Bump @slack/bolt and prism to latest versions

- src/interfaces/assistants_web/src/components/UI/CopyToClipboardButton.tsx
- src/interfaces/assistants_web/src/hooks/use-fixCopyBug.ts
When the client is loaded over HTTP the clipboard is disabled. In that case, it's probably better to have the clipboard copy fix hook fall back to the default behaviour. In addition, let's have the copy button show a hint that the user should set up HTTPS to get the copy button working.
Fixes #797 
This PR introduces a fix for a copy bug, ensuring that the Clipboard API is only used when available over HTTPS.
- Added a check to determine if the Clipboard API is available (`window.navigator.clipboard`) before attempting to use it.
- Updated the button label to display a message indicating that copying requires HTTPS if the Clipboard API is not available.
- Disabled the copy button when the Clipboard API is not available.
- Added a check to prevent the copy function from …
> frontend: Fall back to browser default clipboard behaviour if clipboard API is unavailable

- README.md
- docs/text_to_speech.md
Added documentation for the Text-to-Speech setup.
This PR adds a new section to the README.md file, providing a step-by-step guide on setting up Google Cloud Text-to-Speech. The guide is also available as a separate document, docs/text_to_speech.md.
- A new section is added to the README.md file, titled "How to setup Google Text-to-Speech".
- The new section includes a link to the docs/text_to_speech.md file.
- The docs/text_to_speech.md file is created, containing detailed instructions on setting up Google Cloud Text-to-Speech.
> docs: add text to speech setup guide

- src/interfaces/assistants_web/src/assets/icons/Settings.tsx
- Fixed incorrect viewBox for the settings icon
Before:
After:
This pull request updates the `viewBox` attribute of the SVG element in the `Settings.tsx` file.
- The `viewBox` attribute is changed from `0 0 28 28` to `0 0 32 32`.
> icons: fix settings icon view box

- README.md
Update README.md to make local installation more clear
This pull request introduces changes to the README.md file, providing updated instructions for running the Toolkit application locally and in the cloud. The changes aim to enhance clarity and streamline the setup process for developers.
- **Local Setup**: The section now includes a new subsection titled "Using `make`", which offers an alternative method for running the application locally using a Makefile. It provides a code snippet with commands to clone the repository, navigate to the project directory, and execute the `make first-run` command.
- **Docker Compose**: The previous "Docker Compose setup" section has been replaced with a new subsection titled "Docker Compose only". This section provides instructions …
> Docs: Update README.md to make local installation more clear

- src/interfaces/assistants_web/src/components/Composer/DataSourceMenu.tsx
- src/interfaces/assistants_web/src/components/MessagingContainer/AssistantTools.tsx
- src/interfaces/assistants_web/src/components/MessagingContainer/Welcome.tsx
Allow toggling tools for custom Assistants too
This pull request makes changes to the `DataSourceMenu.tsx`, `AssistantTools.tsx`, and `Welcome.tsx` components.
The changes remove the `checkIsBaseAgent` function from the imports and usage in the `DataSourceMenu.tsx` and `AssistantTools.tsx` components. Instead, the `isBaseAgent` variable is replaced with a `paramsTools` variable, which is used to determine the number of tools and the state of the switch component.
- The `checkIsBaseAgent` function is removed from the imports in `DataSourceMenu.tsx` and `AssistantTools.tsx`.
- In `DataSourceMenu.tsx`, the `isBaseAgent` variable is replaced with a `paramsTools` variable, which is used to determine the number of tools and the state of the switch component.
- In …
> frontend: Allow toggling tools for non-default agents

- src/backend/database_models/group.py
- src/backend/database_models/user.py
These relationship overlap but in a harmless way, we explicitely add the overlap field here in the sqlalchemy models to silence the warning. 
This PR updates the `user_associations` relationship in the `Group` and `UserGroupAssociation` classes to include the `overlaps` parameter.
- In `Group`, the `user_associations` relationship is updated to include the `overlaps` parameter with the value `"groups,users"`.
- In `UserGroupAssociation`, the `group` relationship is updated to include the `overlaps` parameter with the value `"groups,user_associations,users"`.
> chore: Fix Groups/UserGroupsAssociation table overlap issue

- src/interfaces/assistants_web/src/components/HotKeys/HotKeysProvider.tsx
- src/interfaces/assistants_web/src/components/SideNavPanel/SideNavPanel.tsx
- src/interfaces/assistants_web/src/components/UI/Icon.tsx
- src/interfaces/assistants_web/src/stores/persistedStore.ts
- src/interfaces/assistants_web/src/stores/slices/settingsSlice.ts
There is a modal dialog that already exists in the Assistants Web interface, that shows the available keyboard shortcuts. This modal dialog can already be accessed by pressing Ctrl + K or Cmd + K.
This PR modifies the left navigation menu to include a "Hot Keys" button that can be used to access the hot keys dialog:
When hovering over the button, it shows the keystroke to the right:
This PR introduces a new feature for managing hotkeys in the application. The changes include:
- **src/interfaces/assistants_web/src/components/HotKeys/HotKeysProvider.tsx**:
- The `useSettingsStore` hook is imported from `@/stores`.
- The `useState` hook is removed, and the `isHotKeysDialogOpen` and `setIsHotKeysDialogOpen` states are now managed using the `useSettingsStore` hook.
- The …
> Assistants Web: Add hot key bindings button

- src/interfaces/assistants_web/src/components/MessagingContainer/MessagingContainer.tsx
- Changed the way of importing the `ScrollToBottom` component to avoid  the `Prop “className” did not match` warning. 
The PR introduces changes to the `src/interfaces/assistants_web/src/components/MessagingContainer/MessagingContainer.tsx` file. The main modification involves the import statements, where the `ScrollToBottom` component is now imported dynamically using the `dynamic` function from the `next/dynamic` module. This dynamic import ensures that the component is only loaded when needed, improving the performance and reducing the initial bundle size.
- Added `import dynamic from 'next/dynamic';` to enable dynamic imports.
- Replaced `import ScrollToBottom, { useScrollToBottom, useSticky } from 'react-scroll-to-bottom';` with `import { …
> frontend: fix react-scroll-to-bottom import

- Makefile
- Added the ability to specify a specific test for unit and community tests
This pull request modifies the `Makefile` to enhance the test execution process by introducing a new variable, `$(file)`, in the `run-unit-tests` and `run-community-tests` targets.
- In the `run-unit-tests` target, the command has been updated to `poetry run pytest src/backend/tests/unit/$(file) --cov=src/backend --cov-report=xml`.
- Similarly, the `run-community-tests` target now includes the variable `$(file)` in the command: `poetry run pytest src/community/tests/$(file) --cov=src/community --cov-report=xml`.
The addition of the `$(file)` variable allows for more flexibility in specifying the test file or pattern to be executed, enabling more granular control over the test …
> tests: add the ability to specify a specific test for unit and community tests

- src/backend/chat/custom/tool_calls.py
- src/backend/tests/unit/chat/test_tool_calls.py
- src/backend/tests/unit/configuration.yaml
- src/backend/tools/base.py
- src/backend/tools/brave_search/tool.py
- src/backend/tools/google_search.py
- src/backend/tools/hybrid_search.py
- src/backend/tools/tavily_search.py
- Improves Hybrid search tool implementation
- Removes reranking from leaf tools, and instead have the main Hybrid Search tool perform rerank on all aggregated results
- Use .get() instead of mydict["key"] to avoid KeyError exceptions
- Add better tool error handling in no results scenario or tool auth failure scenarios
This PR introduces several changes to the backend tools and configuration, primarily focusing on error handling, search functionality, and tool authentication.
- **Error Handling:**
- A new `ToolError` class is introduced in `src/backend/tools/base.py` to handle tool-related errors.
- The `ToolErrorCode` enum is added to categorize error types.
- The `ToolAuthException` class is defined to handle tool authentication exceptions.
- The `_call_tool_async` …
> backend: Hybrid Search improvements

- .github/workflows/frontend_assistants_web_tests.yml
- .github/workflows/frontend_coral_web_tests.yml
- .github/workflows/frontend_slack_bot_tests.yml
- src/interfaces/assistants_web/src/cohere-client/generated/schemas.gen.ts
- src/interfaces/assistants_web/src/cohere-client/generated/types.gen.ts
> chore(frontend): Add CI to check client is properly generated for coral/assistants

- .env-template
- docs/config_details/config_description.md
- src/backend/chat/custom/custom.py
- src/backend/config/configuration.template.yaml
- src/backend/config/settings.py
- src/backend/services/chat.py
- src/backend/tools/base.py
Improving chat responses using preambles
This PR introduces a new feature called `USE_TOOLS_PREAMBLE` to enhance the model's tool usage. It involves several changes across multiple files:
- **src/backend/config/settings.py**:
- A new field `use_tools_preamble` is added to the `ToolSettings` class, with a default value of `False`.
- **src/backend/config/configuration.template.yaml**:
- The `use_tools_preamble` field is added with a value of `true`.
- **src/backend/chat/custom/custom.py**:
- The `generate_tools_preamble` function is imported from `backend.services.chat`.
- A new conditional block is added to the `call_chat` function, which sets the `chat_request.preamble` using the `generate_tools_preamble` function if `chat_request.tools` is not empty and the …
> TLK-2361 - Tools preamble extension

- README.md
- docs/custom_tool_guides/tool_auth_guide.md
- docs/setup.md
- docs/walkthrough/walkthrough.md
- src/backend/config/configuration.template.yaml
This PR introduces several changes to the Cohere Toolkit documentation, focusing on setup instructions, tool authentication, and configuration.
- **README.md**: The local setup instructions now include the installation of [Poetry](https://python-poetry.org/docs/#installation) alongside Docker and Docker Compose.
- **docs/setup.md**: The setup guide has …
> docs: Update setup docs

- Makefile
This PR introduces changes to the `Makefile`, primarily focusing on the `check-config` target and related tasks.
The `check-config` target has been split into two separate targets: `check-config-install` and `check-config`. The former now handles the installation process, while the latter is responsible for running the configuration check. This separation enhances clarity and modularity in the build process.
- Added a new target `check-config-install` to handle the installation process.
- Modified the `check-config` target to only run the configuration check.
- Added a new line `make check-config` to the `dev` target, ensuring the configuration check is executed during development.
> chore: Check config when running `make dev`

- src/interfaces/coral_web/package-lock.json
- src/interfaces/coral_web/package.json
This PR introduces a new dependency, `cross-spawn`, to the `package.json` and `package-lock.json` files.
- Adds the `cross-spawn` dependency to the `package.json` file.
- Updates the `package-lock.json` file with the new `cross-spawn` dependency, including its `version, `resolution URL, and `integrity hash.
> security: Update cross-spawn in coral_web

- src/backend/scripts/cli/constants.py
This PR updates the `ENV_YAML_CONFIG_MAPPING` dictionary in the `constants.py` file. The change involves modifying the path for the `TAVILY_API_KEY` entry, which now points to `tools.tavily_web_search.api_key`.
- The `TAVILY_API_KEY` path is updated from `tools.tavily.api_key` to `tools.tavily_web_search.api_key`.
- A comment is added, suggesting the …
> bug: Fix `make first-run` command not setting proper Tavily api_key config

- src/backend/routers/chat.py
- src/backend/services/chat.py
- src/backend/tests/unit/factories/agent.py
- src/backend/tests/unit/routers/test_chat.py
- src/interfaces/assistants_web/src/app/(main)/(chat)/Chat.tsx
- src/interfaces/assistants_web/src/app/(main)/edit/[agentId]/UpdateAgent.tsx
- src/interfaces/assistants_web/src/app/(main)/new/CreateAgent.tsx
- src/interfaces/assistants_web/src/components/AgentSettingsForm/ConfigStep.tsx
- src/interfaces/assistants_web/src/components/AgentSettingsForm/index.tsx
- src/interfaces/assistants_web/src/components/UI/Slider.tsx
- src/interfaces/assistants_web/src/components/UI/index.ts
- src/interfaces/assistants_web/src/constants/conversation.ts
- src/interfaces/assistants_web/src/stores/slices/paramsSlice.ts
Added the Slider Component from the Coral Web interface to the Assistants Web interface.
Added Temperature Setting to Assistant Create and Update forms. This setting is then used when chatting with the assistant.
This PR introduces a new `temperature` parameter to the `AgentSettingsForm` component and its associated types, allowing users to set the temperature for agents. The `temperature` parameter is now included in the `CreateAgentSettingsFields` and `UpdateAgentSettingsFields` types, as well as in the `ConfigStep` component.
- The `temperature` parameter is added to the `AgentSettingsForm` component's `ConfigStep` component, allowing users to set the temperature for agents.
- The `temperature` parameter is included in the `CreateAgentSettingsFields` and …
> frontend: added temperature gauge to assistant form

- src/backend/config/routers.py
The PR removes the `DEFAULT_AGENT` attribute from the `RouterName` class in `src/backend/config/routers.py`.
- The `DEFAULT_AGENT` attribute is removed from the `RouterName` class.
> chore: Remove deprecated default_agent router in config

- .github/workflows/backend_integration_tests.yml
- .github/workflows/backend_lint.yml
- .github/workflows/backend_typecheck.yml
- .github/workflows/backend_unit_tests.yml
Only run CI/CD workflows when necessary to reduce GitHub Actions billing
This PR updates the GitHub workflows for backend integration tests, linting, type checking, and unit tests. The changes ensure that the workflows are triggered only when changes are made to the `src/backend` directory.
- The `branches` field is updated to include only the `main` branch.
- A new `paths` field is added to specify the `src/backend` directory as the target for changes.
- The `pull_request` field is updated to include the `paths` field, ensuring that pull requests are triggered only when changes are made to the specified path.
> Infra: reduce workflow runs

- src/backend/services/cache.py
- **Description:** Update redis to use newer `hset` function instead of deprecated `hmset`.
- **Issue:** Fixes #915 
- **Dependencies:** No dependency changes
This pull request updates the `cache_put` function in the `cache.py` file. The function now uses the `hset` method instead of `hmset` to set the key-value pair in the cache.
- In `cache.py`, the `cache_put` function now uses `client.hset(key, value)` instead of `client.hmset(key, value)`.
> refactor: update deprecated hmset function to hset

- src/backend/chat/custom/custom.py
- src/backend/chat/custom/utils.py
- src/backend/routers/chat.py
- src/backend/routers/conversation.py
- src/backend/services/conversation.py
Noticed that the session in the `get_deployment` method was not being patched by the fixture. Decided to pass request session through function calls to ensure the same session is being used for all db requests.
This PR introduces a new `session` parameter to the `get_deployment` function in src/backend/chat/custom/utils.py, which is then used in various other functions and methods across the codebase.
- The `get_deployment` function now takes an additional `session` parameter of type `Session`.
- The `session` parameter is then passed to the `deployment_service.get_deployment_instance_by_name` function, replacing the previous `session = next(get_session())` line.
- The `CustomChat.chat` method in src/backend/chat/custom/custom.py now takes a new `session` parameter, …
> Backend: Fix DB session not being patched by test fixture

- src/interfaces/assistants_web/src/app/(main)/settings/Connection.tsx
- src/interfaces/assistants_web/src/app/(main)/settings/Settings.tsx
- src/interfaces/assistants_web/src/components/Conversation/Header.tsx
Hydration Error caused by client side and server side content rendering not aligning because the client side content depends on data coming from the API and therefore not available during server side rendering. Using useEffect hook to resolve this.
This pull request introduces changes to the `Header.tsx` component in the `src/interfaces/assistants_web/src/components/Conversation` directory. The modifications primarily focus on enhancing the rendering of the header section, ensuring a more dynamic and responsive user interface.
**Changes:**
- The `useEffect` hook is added to resolve a hydration error related to server-side and client-side content alignment.
- A new `useState` hook is introduced, initializing a state variable `init` to `false`.
- The rendering of the …
> Front End: Resolve hydration error found in Conversation Header

- docs/custom_tool_guides/slack.md
Slack tool documentation updates
This PR updates the Slack documentation to improve clarity and provide additional guidance for setting up environment variables and HTTPS for local development.
**Summary of Changes:**
* **Clarified Section Headings:** Changed "Set Up Environment Variables" to "Set up environment variables" for consistency.
* **Added File Creation Guidance:**  Included a note directing users to the [Toolkit Setup](/docs/setup.md) guide if `configuration.yaml` and `secrets.yaml` files are missing.
* **HTTPS Setup Enhancements:**
* **Environment Variable Update:**  Clarified instructions for updating the `NEXT_PUBLIC_API_HOSTNAME` environment variable in both `.env` and `configuration.yaml` files.
* **Frontend HTTPS Configuration:**
*  Added instructions …
> Slack tool documentation updates
